### ISSUE TITLE
Ligths beams state not being correctly reported

### ISSUE THREAD

**Issue by sky-jreves** [SAIC-iSmart-API/saic-python-mqtt-gateway#104]
Hi.
If I left my lights on when shutting down and locking the doors, it is reported that the beams are off.

**Comment by nanomad** [comment]
If you can repeat the test and log the value of the following topic:

`saic/<EMAIL>/vehicles/<VIN>/lights/mainBeam`
`saic/<EMAIL>/vehicles/<VIN>/lights/dippedBeam`

Maybe it's a decoding error in the Home Assistant integration

if the values are stuck to "False", then logging of this topic is also required:

`saic/510_25857/json/response`
`saic/511_25857/json/response`

**Comment by tosate** [comment]
Hi @sky-jreves 

first of all sorry for the late response. I think we need to distinguish the different types of lamps of the car. The manual mentions the following ones:

- Daytime Running Lamps
- Dipped Head Lamps
- Head Lamp High Beam

According to the [ZS manual](https://www.mg.co.uk/sites/default/files/2021-11/New%20MG%20ZS%20EV%20Owner%20Manual.pdf) (pages 40 to. 41), the dipped head lamps and the high beam operate when the START/STOP switch is in the ON/READY position.

The API offers the boolean fields:

- dippedBeamStatus
- mainBeamStatus

From my point of view, those field can get the value `true` only if the START/STOP switch is in the ON/READY position. Unfortunately, this won't help you when your car is switched OFF and the are still lights on.

Nevertheless, I have never seen so far that the mainBeamStatus had the value `true` on my ZS. I went multiple times through the implementation, but I cannot find a reason for this. Maybe this behaves different for other MG models.
