### ISSUE TITLE
Charging Station Configuration - benefits?

### ISSUE THREAD

**Issue by svenove** [SAIC-iSmart-API/saic-python-mqtt-gateway#105]
The ReadMe states:
> If your charging station also provides information over MQTT or if you somehow manage to publish information from your charging station, **the MQTT gateway can benefit from it.**

It might be a stupid question, but what exactly does the MQTT gateway do with the charge station information that is benefical?
I have an Easee charging station and could easily add it to configuration-file, but I'm not seeing what exactly will happen if I do so...

**Comment by tosate** [comment]
There is no way to detect when your car starts charging. The SAIC API offers no notification for this like it does for the motor start event. Therefore we have configured a default interval of 10 minutes where we query the vehicle state after the engine was turned off. With a bit of luck, we detect that the car gets charged in this period.

However, if you configure your charging station to use the energy surplus of a photovoltaic system, the charging may start at any time and the gateway cannot detect this.
But maybe you have a charging station that publishes the start of the charging as a MQTT topic. Then you can configure this and the gateway will detect the start of the charging.

**Comment by svenove** [comment]
Ah, good point! 
I "solved" that by adding a simple automation - "if charger changes to busy-charging, then force refresh from SAIC".
But I'll try adding directly to SAIC - perhaps that works even better than my workaround. :)
