### ISSUE TITLE
Target SoC entity missing

### ISSUE THREAD

**Issue by jfreves** [SAIC-iSmart-API/saic-python-mqtt-gateway#107]
Hi.
I have no entity for Target SoC, I have the current value and all the charging related entities but no for target SoC.
If I set it up through the gateway an update is published through target SoC topic but no entity is created and it seems that no updates to this topic is made in any other situation.
Regards.

**Comment by nanomad** [comment]
Can you check if you have the following topic?

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/1129926/34d00f7a-e310-4600-889a-c786bc1cf2c4)

If not please provide a dump of:
- saic/<email>/vehicles/<vin>/configuration/raw
- saic/<email>/vehicles/<vin>/drivetrain/socTarget

**Comment by jfreves** [comment]
This is the dump of `homeassistant/number/<vin>_mg/<vin>_target_soc/config`

```
{
    "name": "Target SoC",
    "device": {
        "name": "MG MG4 Electric <vin>",
        "manufacturer": "MG",
        "model": "MG4 Electric 2022 PAG/PBC",
        "hw_version": "EH32 S",
        "identifiers": [
            "<vin>"
        ]
    },
    "unique_id": "<vin>_target_soc",
    "object_id": "<vin>_target_soc",
    "availability_topic": "saic/_internal/lwt",
    "payload_available": "online",
    "payload_not_available": "offline",
    "state_topic": "saic/jorgefreves@outlook.com/vehicles/<vin>/drivetrain/socTarget",
    "command_topic": "saic/jorgefreves@outlook.com/vehicles/<vin>/drivetrain/socTarget/set",
    "value_template": "{{ value }}",
    "retain": "false",
    "mode": "slider",
    "min": 40,
    "max": 100,
    "step": 10,
    "enabled_by_default": false,
    "device_class": "battery",
    "unit_of_measurement": "%",
    "icon": "mdi:battery-charging-70"
}
```

**Comment by nanomad** [comment]
Ah that's it, there's a bug in the code enabling this sensor. For the time being you can enable it manually in HA by going into settings -> Devices and Services -> MQTT -> Devices -> MG4 -> Controls and under there you should have an option to see disabled entities

**Comment by jfreves** [comment]
Thanks for your help, that worked
