### ISSUE TITLE
control seat heating

### ISSUE THREAD

**Issue by mrniemand** [SAIC-iSmart-API/saic-python-mqtt-gateway#112]
is it anyhow possible to switch on the seat heating? In the original app its possible (unfortunally not the stearing wheel heating)

**Comment by TripelJ** [comment]
@mrniemand Which car do you have that allows control og the seat heating from the iSMART app ? 
I have a Marvel R and that is not possible in the new or old app for iOS.

**Comment by mrniemand** [comment]
i have an MG4 trophy. It was allready in the old app

**Comment by nanomad** [comment]
Closing as duplicate of #127
