### ISSUE TITLE
How to get trip data?

### ISSUE THREAD

**Issue by bjoernkowarsch** [SAIC-iSmart-API/saic-python-mqtt-gateway#117]
Hi, I was wondering how you guys get the data for an individual trip? From what I can see, there is no dedicated parameter (as opposed to many other car manufacturers apis), all which is there for me is "mileage_of_the_day", which aggregates all trips of a day. And there is mileage_since_last_charge, which seems to aggregating as well and resets whenever the car bets charged e.g. recharged.

So are you calculating trip data from any of these? If so, how?

**Comment by nanomad** [comment]
I've had a play with the API data....looks like we have trip info available:

![telegram-cloud-photo-size-4-6014782019793437160-y](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/1129926/5e5c0cee-9c4d-4faf-8d30-9ec4d917a02d)

We can expose the "last trip mileage" counter to HA, it seems more reliable than "since last charged" and "since today"

**Comment by bjoernkowarsch** [comment]
I thought nobody would comment on this, so thank you @nanomad for getting back to me. Initially I played with "last_trip_mileage" in HA, but it gave me wrong readings. I eventually realized that it gets resetted at around 4pm each day. So I concluded it must have anything to do with a (wrong) time zone. But I am unaware where to set it. Even in the app I could not see anything with regards to this.

Do you have any idea?

**Comment by nanomad** [comment]
Does the trip id change as well? I've just started investigating this yesterday night ☺️

I can definitely confirm that the other mileage values are useless as they get reset randomly as well (but we can compute at least the since last charged via automation so that's not a big deal)

**Comment by bjoernkowarsch** [comment]
Kudos for investigating! With rgds to Trip ID - not sure, I need to check. Need to do some driving beforehand, the car is sitting in the garage for 2 weeks now. Will update ...

**Comment by nanomad** [comment]
@bjoernkowarsch I'm releasing the "current trip distance" sensor (disabled by default) with 0.6.X.

**Comment by leocrawford** [comment]
This is really helpful, but ideally it would be great to also have the energy used for that trip, and perhaps the trip ID and the calculated distance/trip (as attributes). I do see this isn't in the raw data, so would require calculating by finding the difference between the SoC at the beginning and end of trip - which is non trivial.

**Comment by nanomad** [comment]
We can publish the trip id, I'd rather not complicate the gateway further as there may be charging sessions during the trip that could skew the result

**Comment by leocrawford** [comment]
Thank you very much for publishing the trip ID.  It will at least allow me to correlate a start and end journey, and make sure they match (and that I haven't missed an event)

I can see the logic in not creating anything more complex, though the idea of a journey does seem to be a first class citizen of the API and we will have to piece it together from other sources. For example, even with the ID and trip mileage (above) the start and end times will have to be gathered from when the event arrives (and it could be deferred) so whilst it might make sense to not add any details (e.g. energy use) which can only be estimated not derived from the API it would be lovely to have the attributes we do have for a journey as an atomic element.

For info, I  have the following which others may find useful to pull out journey stats.  I'll update it soon with the new data we have, Thank you!

>   # Journey Start - Triggered when vehicle starts running
>   - trigger:
>       - platform: state
>         entity_id: binary_sensor.mg_zorro_vehicle_running
>         from: "off"
>         to: "on"
>     sensor:
>       - name: "MG Zorro Journey Start"
>         unique_id: mg_zorro_journey_start
>         state: "{{ states('device_tracker.mg_zorro_vehicle_position') }}"
>         attributes:
>           start_time: "{{ now().isoformat() }}"
>           start_temperature: "{{ states('sensor.mg_zorro_exterior_temperature') | float }}"
>           start_lat: "{{ state_attr('device_tracker.mg_zorro_vehicle_position', 'latitude') }}"
>           start_lon: "{{ state_attr('device_tracker.mg_zorro_vehicle_position', 'longitude') }}"
>           start_energy: "{{ states('sensor.mg_zorro_energy_usage_since_last_charge') | float }}"
>           start_odo: "{{ states('sensor.mg_zorro_mileage_since_last_charge') | float }}"
>           start_soc: "{{ states('sensor.mg_zorro_soc') | float }}"
>           start_range: "{{ states('sensor.mg_zorro_range') | float }}"
> 
>   # Journey Complete - Triggered when vehicle stops running
>   - trigger:
>       - platform: state
>         entity_id: binary_sensor.mg_zorro_vehicle_running
>         from: "on"
>         to: "off"
>     sensor:
>       - name: "MG Zorro Journey"
>         unique_id: "mg_zorro_journey"
>         state: >
>           {% set start = state_attr('sensor.mg_zorro_journey_start', 'start_odo') | float %}
>           {% set end = states('sensor.mg_zorro_mileage_since_last_charge') | float %}
>           {% set distance = end - start %}
>           {% set start = state_attr('sensor.mg_zorro_journey_start', 'start_energy') | float %}
>           {% set end = states('sensor.mg_zorro_energy_usage_since_last_charge') | float %}
>           {% set energy_used = end - start %}
>           {% set distance_miles = distance * 0.621371 %}
>           {% if energy_used > 0 %}
>             {{ (distance_miles / energy_used) | round(2) }}
>           {% else %}
>             unavailable divide-by-zero
>           {% endif %}
>         attributes:
>           # Copy Start Data
>           start_time: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_time') }}"
>           start_temperature: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_temperature') }}"
>           start_lat: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_lat') }}"
>           start_lon: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_lon') }}"
>           start_energy: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_energy') }}"
>           start_odo: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_odo') }}"
>           start_soc: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_soc') }}"
>           start_range: "{{ state_attr('sensor.mg_zorro_journey_start', 'start_range') }}"
> 
>           # End Data
>           end_time: "{{ now().isoformat() }}"
>           end_temperature: "{{ states('sensor.mg_zorro_exterior_temperature') | float }}"
>           end_lat: "{{ state_attr('device_tracker.mg_zorro_vehicle_position', 'latitude') }}"
>           end_lon: "{{ state_attr('device_tracker.mg_zorro_vehicle_position', 'longitude') }}"
>           end_position: "{{ states('device_tracker.mg_zorro_vehicle_position') }}" # Full position state
>           end_energy: "{{ states('sensor.mg_zorro_energy_usage_since_last_charge') | float }}"
>           end_odo: "{{ states('sensor.mg_zorro_mileage_since_last_charge') | float }}"
>           end_soc: "{{ states('sensor.mg_zorro_soc') | float }}"
>           end_range: "{{ states('sensor.mg_zorro_range') | float }}"
> 
>           # Calculated Data
>           total_distance: >
>             {% set start = state_attr('sensor.mg_zorro_journey_start', 'start_odo') | float %}
>             {% set end = states('sensor.mg_zorro_mileage_since_last_charge') | float %}
>             {{ end - start }}
> 
>           total_mileage: >
>             {% set start = state_attr('sensor.mg_zorro_journey_start', 'start_odo') | float %}
>             {% set end = states('sensor.mg_zorro_mileage_since_last_charge') | float %}
>             {{ (end - start) * 0.621371  }}
> 
>           total_energy_used: >
>             {% set start = state_attr('sensor.mg_zorro_journey_start', 'start_energy') | float %}
>             {% set end = states('sensor.mg_zorro_energy_usage_since_last_charge') | float %}
>             {{ end - start }}
> 
>           journey_duration: >
>             {% set start = as_datetime(state_attr('sensor.mg_zorro_journey_start', 'start_time')) %}
>             {% set end = now() %}
>             {{ (end - start).total_seconds() | int }}
> 
>           range_reduction: >
>             {% set start = state_attr('sensor.mg_zorro_journey_start', 'start_range') | float %}
>             {% set end = states('sensor.mg_zorro_range') | float %}
>             {{ (end - start) * 0.621371  }}
> 
>           soc_reduction: >
>             {% set start = state_attr('sensor.mg_zorro_journey_start', 'start_soc') | float %}
>             {% set end = states('sensor.mg_zorro_soc') | float %}
>             {{ end - start  }}
