### ISSUE TITLE
Heated seat functionality missing

### ISSUE THREAD

**Issue by Troon** [SAIC-iSmart-API/saic-python-mqtt-gateway#127]
The MG app for my MG4 Trophy now has the ability to turn on the heated seats, with three-level heat control for each seat individually. It'd be amazing if this gateway could do the same.

**Comment by nanomad** [comment]
@Troon I've decoded the new control messages and it is doable. It'll take a while to reach the gateway as we are currently  working on migrating to the new APIs

**Comment by nanomad** [comment]
@Troon should be fixed in 0.5.8, feel free to try once images are built (should take a couple of minutes)

**Comment by sarakha63** [comment]
Confirmed working on my side
