### ISSUE TITLE
Colors of charging_finished sensor

### ISSUE THREAD

**Issue by GregorEstebanCardosoSchiller** [SAIC-iSmart-API/saic-python-mqtt-gateway#130]
So I detected that my MG4 is on 80% (not climbing) for more then 2 hours. The SoC is at 80% the kwh are at 51,2. But the car still drains energy from the wallbox, for over two hours.

What does the sensor charging_finished indicate with its colors?

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/65222903/06089deb-b9fa-4c38-941d-4205efad7eb9)

When glimpsing into the car I think I saw a symbol with a battery and a exlamaction mark which indicates due to the informaton to too high temperatur of the high volt battery. Any ideads regarding that? We habe -1 degree Celsius outside and it is not the first time, that the car loads far longer, besides being "full".

**Comment by nanomad** [comment]
The color is kind of useless for this kind of sensor, it indicates the expected time for a complete charge (either 100% or whatever you have as the in-car charging limit).

What you could be seeing is the cells re-balancing. MG4 Luxury does that at every charging "threshold" (altough true balacing is done at 100%)
