### ISSUE TITLE
Is it possible add a new environment variable to configure the timezone?

### ISSUE THREAD

**Issue by ppnacho** [SAIC-iSmart-API/saic-python-mqtt-gateway#132]
The default timezone is America, if it is possible add an environment variable TZ to configure the timezone. Thanks

**Comment by sarakha63** [comment]
TZ variable is already working on the docker compose

**Comment by ppnacho** [comment]
Ah, OK, Sorry, in the documentation I don't see this variable.

**Comment by ppnacho** [comment]
The content in docker compose,

version: "3.1"

services:
  saic-mqtt-gateway:
    image: "saicismartapi/saic-python-mqtt-gateway:latest"
    container_name: "saic-mqtt-gateway"
    environment:
      - MQTT_URI=${MQTT_BROKER_URI}
      - MQTT_USER=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PWD}
      - SAIC_USER=${SAIC_USERNAME}
      - SAIC_PASSWORD=${SAIC_PWD}
    volumes:
      - ./charging-stations.json:/usr/src/app/charging-stations.json
      
I don't see the TZ in environment.

Thanks

**Comment by sarakha63** [comment]
Just add it in the environnement section it is a common environnement variable system based juste like the user and group ids one
