### ISSUE TITLE
[BUG] Case Blowing Only ---> invalid payload

### ISSUE THREAD

**Issue by sarakha63** [SAIC-iSmart-API/saic-python-mqtt-gateway#134]
Hello team

There is an issue with the remote climate set mode blowingOnly. I had issue with it and decided to dig into the code

and

in the mqtt_gateway.py file

there is a switch case condition for all modes

and the switch is based on  msg.payload.decode().strip().lower()
which will always be lowercase

and the case 

`case 'blowingOnly':
                            LOG.info('A/C will be set to blowing only')
                            self.saic_api.start_ac_blowing(self.vin_info)`
                            

Can never happen in fact 

;)

**Comment by Tonno87** [comment]
I can confirm the problem:

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/734174b7-aeea-4336-bfbe-985114bdc2ed)
