### ISSUE TITLE
Can the figures (currently in KM) be presented in HA as Miles?

### ISSUE THREAD

**Issue by daknightuk** [SAIC-iSmart-API/saic-python-mqtt-gateway#139]
Can the figures (currently in KM) be presented in HA as Miles? I'm in the UK

**Comment by nanomad** [comment]
@daknightuk Does the value reported by HA correctly represents the figure in miles? I.e. it's just the displayed unit that is wrong

**Comment by daknightuk** [comment]
@nanomad No the number represents the figure in KM only now whilst I "could" create a filter template in HA this would mean creating one for each reading in KM to convert it to miles and let me be honest that would then double the number of entities and make HA both confusing and a hassle when writing automations. Ideally (like on the MG app) there should be an option to switch between Miles and KM and some simple maths in the background i.e KM divided into 0.62137119 = Miles.

**Comment by Troon** [comment]
HA will do this for you:

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/1823375/9973b750-606d-4aeb-bbf0-6a3328167593)

**Comment by nanomad** [comment]
I guess we can close this as not needed if it can be easily configured in HA without creating new templates

**Comment by daknightuk** [comment]
@Troon thank you so much for this I had no idea you could do this on HA :)
