### ISSUE TITLE
Token expired error - GW does not fetch new token

### ISSUE THREAD

**Issue by cybersmart-eu** [SAIC-iSmart-API/saic-python-mqtt-gateway#144]
I found that error message in the logs repeating now for more than 40 Minutes since I used the App (and closed it again).

Expected behaviour would be that GW fetches the login again and gets a new token.

When manually restarting container the login is immeditely fetched by the Gateway.

![IMG_1087](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/77569473/19887a7b-5e62-4ea5-aedc-5ab52188714f)

**Comment by nanomad** [comment]
@cybersmart-eu should be fixed in 0.5.2, docker image is build so feel free to try and report back

**Comment by nanomad** [comment]
@cybersmart-eu It is

**Comment by cybersmart-eu** [comment]
ok, can confirm issue fixed, after 15 Minutes (900s) login has been fetched by GW.
