### ISSUE TITLE
Feature Request: Start/Stop charging

### ISSUE THREAD

**Issue by ma-martins** [SAIC-iSmart-API/saic-python-mqtt-gateway#15]
Hello,
It would be nice to be able to control the car charging with start/stop via this integration for energy management purposes (automations with energy consumption and solar production readings etc).

An added bonus to be able to set the maximum SOC it charges up to.

Is this doable?

Thanks

**Comment by tosate** [comment]
I think this is doable, but we need to reverse-engineer the API messages first.
The [documentation](https://github.com/SAIC-iSmart-API/documentation) does not cover this topic yet.

**Comment by Dargish** [comment]
+1 for this, I came here to ask about setting maximum SoC. I have been using this project to get information into Home Assistant which works very well, the only thing I regularly used from the app that it's missing is being able to set the target SoC.

**Comment by nanomad** [comment]
I've been playing with it for the last couple of days, and the reliabilty of the "start charging" command is very hit and miss. Setting the target SoC seems to be fine, as well as stopping an ongoing charge.
