### ISSUE TITLE
totalBatteryCapacity Value for MG4 ER 77kWh

### ISSUE THREAD

**Issue by mpetereit** [SAIC-iSmart-API/saic-python-mqtt-gateway#152]
I just got an MG4 Trophy Extended Edition and connected the script with mqtt in ioBroker.

The value "totalBatteryCapacity" is telling me that I have an 64kwh Battery but the Trophy Extended Edition has a 77kwh Battery.
Is the Information comming directly from the saic Service or is it calculated somewhere in the script?

My guess is that its comming wrong from the saic service because the Manufacturing Date of the car is wrong too (showing 2022 instead of 2023)

**Comment by nanomad** [comment]
The SAIC API has wrong values across all vehicles, you can either specify your raw capacity from the config or if you post here the hardware version (e.g. EH32 S for the MG4 luxury, as shown in HA) we can prepare a new release that corrects the value

**Comment by mpetereit** [comment]
Good to know :D

The MG4 Trophy Extended Range has the Hardware Version "EH32 X3"

**Comment by nanomad** [comment]
@mpetereit Feel free to try the 0.5.11 docker image, it should report 77kWh now

**Comment by mpetereit** [comment]
@nanomad 
The change you made is not working yet but after reviewing the fix you made i understand why.

You are checking the "series" value. For me it shows "EH32 S", but the "model" value shows "EH32 X3". Sorry bout the mixup...
So it looks like that you also have to take the model value into account when rewriting the capacity.

So my output is:
model = EH32 X3
series = EH32 S

**Comment by nanomad** [comment]
Ah that makes a lot more sense actually, It's a Thropy series (EH32 S) with the Extended range variant (EH32 X3). I'll change the code accordingly

**Comment by nanomad** [comment]
@mpetereit Can you re-test with 0.5.13?

**Comment by mpetereit** [comment]
@nanomad
Looks good now, thanks :)

If you need any other data, let me know. Maybe for other Features/tests

**Comment by cybersmart-eu** [comment]
I‘d like to add 2 configurations here (might not be in database already)

MG5 SR Comfort
Model: MG5 Electric
Series: EP2CP3

Battery Capacity:
nominal: 50.3 kWh
usable: 46.0 kWh

—-
MG4 XPOWER
Model: EH32 X4
Series: EH32 S

Battery Capacity: 
nominal: 64.0 kWh
usable: 61.7 kWh

**Comment by nanomad** [comment]
The XPOWER uses the same series code as the lux, so we are good there. I'll add the MG5 SR Comfort to the list

**Comment by nanomad** [comment]
@cybersmart-eu should be fixed in v0.5.15

**Comment by cybersmart-eu** [comment]
Thx Giovanni,

BR
Uwe
