### ISSUE TITLE
FR: Home Assistant sensor for DRIVETRAIN_HV_BATTERY_ACTIVE

### ISSUE THREAD

**Issue by bj00rn** [SAIC-iSmart-API/saic-python-mqtt-gateway#153]
It would be nice to have a sensor for DRIVETRAIN_HV_BATTERY_ACTIVE

I just realised looking at the logs, that that the rear window heating does not activate the HV battery and could potentially drain the 12V battery. It would be nice to have a sensor to look out for stuff like this.

**Comment by nanomad** [comment]
@bj00rn Easy enough :)

keep in mind that the flag is our deduction and is computed as:

`self.is_charging or is_engine_running or remote_climate_status > 0`

Did you check if contactors did close during rear window heating?

**Comment by bj00rn** [comment]
> @bj00rn Easy enough :)
> 
> keep in mind that the flag is our deduction and is computed as:
> 
> `self.is_charging or is_engine_running or remote_climate_status > 0`
> 
> Did you check if contactors did close during rear window heating?

Hmm, I see. Not as straightfoward as I tought then. Will check the contactor

**Comment by bj00rn** [comment]
@nanomad My bad, it seems the contactors are closed when the rear heating is activated. I guess the conditions for DRIVETRAIN_HV_BATTERY_ACTIVE could be updated to include rear window heating, but maybe it's not worth the effort..

**Comment by nanomad** [comment]
Should be fixed in v0.6.0-rc3 Pre-release

**Comment by nanomad** [comment]
Closing as completed, feel free to open a new issue if this happens again
