### ISSUE TITLE
Heated seat oddity vs app on RHD cars

### ISSUE THREAD

**Issue by Troon** [SAIC-iSmart-API/saic-python-mqtt-gateway#155]
The new heated seat functionality is amazing: thanks for implementing.

I turned the right-side heated seat on via Home Assistant, then switched over to the app to check. It has labelled the right-side seat as heating but the "Medium" label is under "Passenger". The app does not behave like this when it is used to switch on the seats: text and picture are aligned. This is just a minor cosmetic issue, as I have verified that the right-hand seat is heating up (picture and HA entities are correct, app text is wrong).

I would be quite happy with a "won't fix" response.

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/1823375/855afbd3-3196-4af1-9314-3fa3126ac841)

**Comment by nanomad** [comment]
Uhm, it's actually not minor as it may indicate an inconsistency somewhere in the command being sent, altough I have a feeling the label is handled by the in-app logic somehow.

Can you re-test by starting the right seat heater and see how the status changes on HA / MQTT? A JSON capture of the payload would be nice as well (for both the start command from HA, start response from HA, vehicle and charging status when started from the app, vehicle and charging status when started from HA)

**Comment by Troon** [comment]
Looks like you're right about it being fixed within the app: older versions had it the wrong way around:

https://www.mgevs.com/threads/heated-seats-bug-altered-not-improved.14624/
