### ISSUE TITLE
When using gateway my ismart app token constantly expires

### ISSUE THREAD

**Issue by daknightuk** [SAIC-iSmart-API/saic-python-mqtt-gateway#156]
When using gateway my ismart app token constantly expires

I have to log into my ismart app every time I open it. I think this is something to do with the logon token and am thinking that the [saic-python-mqtt-gateway](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway) has an active token making the one on my ismart app not work?

Does anyone else have this same problem?

**Comment by cybersmart-eu** [comment]
Known issue from SAIC Server side. Only one ne active login (valid token) at a time.Works as designed (by SAIC), GW can do nothing about it.Am 02.02.2024 um 12:43 schrieb daknightuk ***@***.***>:﻿
When using gateway my ismart app token constantly expires
I have to log into my ismart app every time I open it. I think this is something to do with the logon token and am thinking that the saic-python-mqtt-gateway has an active token making the one on my ismart app not work?
Does anyone else have this same problem?

**Comment by NicolaiPetri** [comment]
Do anyone know the lifetime of a login token ? If it is long-lived, then it might be smartest just to copy it from the phone after login ?
