### ISSUE TITLE
Heated seats not shown in control or debug info fl MG5 LR luxury 5.10

### ISSUE THREAD

**Issue by kimtatti** [SAIC-iSmart-API/saic-python-mqtt-gateway#158]
Heated seats that came in version 5.8 not shown in update 5.10.
Updated from 5.4 to 5.10.

**Comment by Tonno87** [comment]
On this [Page](https://github.com/SAIC-iSmart-API/documentation/blob/main/docs/examples/v1_1/501_513.adoc) you can see the known car configurations. 
There is no way to activate your heated seats by app/gateway.
