### ISSUE TITLE
Heated seats - status

### ISSUE THREAD

**Issue by MB1983k** [SAIC-iSmart-API/saic-python-mqtt-gateway#161]
Is it maybe also possible to see the status of the heated seats?

Is there maybe also a possibility to set the seat cooling function?

**Comment by cybersmart-eu** [comment]
Which of the MG has cooling function for heats? Missing that in my MG4 as well ;-) but is there any model with that function(must be air cooling then)?

**Comment by MB1983k** [comment]
Marvel

**Comment by nanomad** [comment]
> Marvel

Is it available from the app? The status is kind of difficult. To see its feasibility please run this test:
- Start heated seats from the MQTT gateway
- Open the iSmart app
-  Does it show the heated seats as active?

**Comment by billouetaudrey** [comment]
Nope, can't see or change anything from app

**Comment by billouetaudrey** [comment]
> > Marvel
> 
> Is it available from the app?
> 
> The status is kind of difficult. To see its feasibility please run this test:
> 
> * Start heated seats from the MQTT gateway
> * Open the iSmart app
> * Does it show the heated seats as active?


Nope, can't see or change anything from app
