### ISSUE TITLE
MG5 battery heating does not activate

### ISSUE THREAD

**Issue by kimtatti** [SAIC-iSmart-API/saic-python-mqtt-gateway#162]
Facelift MG5 LR will not activate battery heating manually or with scheduler. Battery level 59% and weather is -2 celsius and car stood 16h before attempt to heat. No difference if the car is charging or not. iSmart app does not have battery heating function for this car. Awesome work on this thing btw!

**Comment by cybersmart-eu** [comment]
I am quite sure that there is no remote API command avilabel for MG5 for Battery heating and heated seats as both functions are also not reflected in the iSmart App.

**Comment by kimtatti** [comment]
Yeah that may be true, but API has lots of functions that iSmart does not have. If it does not have this function, then best if removed from control for MG5.

**Comment by cybersmart-eu** [comment]
What domypu mean by „removed from control for MG5“? In iSmart there is no
such funktion. And if SAIC provides this via API however, although not
useful for MG5 this would be a lot of work for the Gateway developers to
individually reflect each car exactly. Maybe over time this can be done
with the community, but I think other topics are more important. Even with
reflecting correct battery sizes in the gateway stromgly depends on
accurate user feedback. With growing community such „cleanup“ might be
feasible in the future but devs are volonteers so I personally don‘t bother
if there seem to be options the car does not support as it is easy to find
out.

BTW: I am very thankful how fast the devs in the last weeks reacted on
feedback and the new API - that was absolutely great to see the community
reporting, devs implementing, community testing, done. Often in minutes not
hours.

kimtatti ***@***.***> schrieb am So. 4. Feb. 2024 um 09:09:

**Comment by kimtatti** [comment]
Sorry, not that familiar with the development prosess. Just meant that like the heated seats option is not in the controls, the battery heating fuction could be removed in future updates if not functional. But other more important thing offcouse first. Probably in the minority, but preconditioning the battery and remote heated seats would be awesome because of the cold weather in Finland. In really cold the battery heating while driving just isnt on long enough that the battery would be warm to charge fast. ZS EV is much better in this sense and tech is really similar. And yeah, just phenomenal job at developing this, Im so grateful that this exist, this makes my life especially in the winter so much easier that with the original iSmart app!

**Comment by cybersmart-eu** [comment]
Unfortunately not every model reflects all internal functions also remotely. MG4 seems to provide most options like heated seats to swichted remotely as well as Battery pre-heating. But for MG5 they don‘t. I own both cars and there is a huge difference.

**Comment by kimtatti** [comment]
> Hi kimtatti, also owning a MG5 LR and afaik battery heating (and enabling / disabling of course) will only work while driving. It should give you exactly that information / notification when you try to enable it via entertainment system when not driving - give it a try.
> 
> This is probably also the reason why you don't find it in the app, as I assume nobody really expects you to use the app while driving.

ZS EV has the heating function in the app and the tech is really similar to MG5. Would of hoped that it is just a limitation of the app that pre heating is not possible in the MG5, but probably its due to the car. A shame, but what can you do.

**Comment by nanomad** [comment]
@cybersmart-eu if the feature is hidden in the app it means it is feature gated by some vehicle feature option (in the vehicle configuration topic). The request seems valid, it's just a matter of reverse egineering the app and figuring out what the check actually is. It may be based on BType.

@kimtatti: Does the iSmart app allow you to set a charge limit %?

**Comment by kimtatti** [comment]
> @cybersmart-eu if the feature is hidden in the app it means it is feature gated by some vehicle feature option (in the vehicle configuration topic). The request seems valid, it's just a matter of reverse egineering the app and figuring out what the check actually is. It may be based on BType.
> 
> @kimtatti: Does the iSmart app allow you to set a charge limit %?

Yes it does. MG5 LR models (the car that I have) with the NMC battery does take a% limit on charge level, but the MG5 SR with LFP doesnt.

**Comment by kimtatti** [comment]
Just seen that this actually works, only thing is that the car switches it on and off automatically. Can be turned off or on thou. And the power of the heating at least at 75% battery and 1.9kw charging is maybe only a few hundred watts. I will test more when the car is not charging etc. Outside temperature has been negative 15-20 celcius this morning.
![IMG_7048](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/146635383/9ee6fabd-caa6-47b9-b1b2-a2ee1ffbbd8d)

**Comment by nanomad** [comment]
@kimtatti I'm closing this as it seems to be  working.
