### ISSUE TITLE
Applying battery_capacity_correction_factor to lastChargeEndingPower

### ISSUE THREAD

**Issue by pmannk** [SAIC-iSmart-API/saic-python-mqtt-gateway#163]
Hi,
It appears the battery_capacity_correction_factor is applied to the totalBatteryCapacity attribute, however it's not also applied to the lastChargeEndingPower attribute?
From what I can tell on my MG4, the correction factor needs to be applied to the lastChargeEndingPower as well.

If I apply the factor manually myself then after charging I get the anticipated outcome, where lastChargeEndingPower equals soc_kwh.

Snippet of the current figures reported in MQTT:
![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/79073108/91d622b7-ca06-4f7a-b596-9e00fac027fa)

Thanks.

**Comment by sarakha63** [comment]
I confirme. With my mg4 luxury behavior is the same

**Comment by nanomad** [comment]
That makes total sense, feel free to open a PR :)

**Comment by nanomad** [comment]
Please try 0.6.0-rc2

**Comment by nanomad** [comment]
Closing as complete
