### ISSUE TITLE
Gateway settings for Australia

### ISSUE THREAD

**Issue by callifo** [SAIC-iSmart-API/saic-python-mqtt-gateway#169]
Hi,

Can anyone assist what I would need to use for Australian servers? Previously I could use '--saic-uri=https://tap-au.soimt.com' and this has worked well, but since upgrading and saic-uri being removed, I am unable to login. 

If I use default settings, I get:
return code: 1000036, message: The account is not registered.

Changing the --saic-region to AU and saic-rest-uri with eu replaced with au, does not work.

**Comment by nanomad** [comment]
Did australia get the "facelift" of the MG app? Or is it still using the classic "black" version?

If so I fear you have to use the old gateway version. If you want to investigate more you can reach me out on telegram (@nanomad)

**Comment by bullantmm** [comment]
I believe I have the same issue... Any further details for configuring for Australia the you could provide would be great!

**Comment by nanomad** [comment]
@bullantmm see if you can provide an answer to the question above

**Comment by jamescreer** [comment]
@nanomad at this point I believe AU and NZ are still using the classic "black" version. 

In the end I rolled back to the old gateway version and it worked again for me in Australia. 
![IMG_8018](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/5995983/22ad431a-350d-440a-b5b1-01aab8332562)

**Comment by bullantmm** [comment]
@jamescreer which version exactly are you using? 0.4.6 or one of the 0.5.x ones? Also are there any other region specific settings that you need for AUS other than --saic-uri=https://tap-au.soimt.com/
?

**Comment by callifo** [comment]
I'm using 0.4.6 according to the changelog in my directory. Was on holiday from the 14th Jan, so wasn't able to test any interim build since. 

For Aus, I did not use any other specific settings except --saic-uri=https://tap-au.soimt.com/

**Comment by jamescreer** [comment]
@bullantmm I'm also running 0.4.6 with https://tap-au.soimt.com as the saic-uri

**Comment by Tonno87** [comment]
@nanomad I will try it out in the next few days. I think it's a good chance to learn more about python and github.

**Comment by nanomad** [comment]
@callifo @bullantmm off topic question... Can you confirm that you see negative values for the latitude in the API responses?

**Comment by bullantmm** [comment]
@nanomad yes position sensor returns negative for latitude (obviously still on 0.4.6 release).

**Comment by hamishfagg** [comment]
NZer here with a MG4 - I can see from DNS logs my phone is looking up these:
```
gateway-au.soimt.com
tap-au.soimt.com
```

The iSmart app reports version 1.0.4 under "My Profile" -> "About"

@nanomad can you say a little more about the work required to make 5.x work for AU/NZ? I'm interested in giving it a go.

**Comment by nanomad** [comment]
@hamishfagg I'd start by refactoring the existing https://github.com/SAIC-iSmart-API/saic-python-client
To expose an API surface similar to the new one https://github.com/SAIC-iSmart-API/saic-python-client-ng

**Comment by bullantmm** [comment]
@hamishfagg have you had a try at this yet? Keen to see how you go - I’d love to be able to update to latest version when new releases come out rather than being stuck on 4.6

**Comment by nanomad** [comment]
@pmannk let's keep this to track the backporting to the legacy version

**Comment by hamishfagg** [comment]
@bullantmm i havent sorry. As usual life has got in the way of me starting something new :P

**Comment by karter16** [comment]
Hi - for what it's worth I've just been playing round with this. I don't know if it's newly available, but https://gateway-mg-au.soimt.com/api.app/v1/ is now available and I have been able to use the latest version of this gateway to connect to my ZS EV.

SAIC_REST_URI: https://gateway-mg-au.soimt.com/api.app/v1/
SAIC_REGION: au

Hope this helps

**Comment by bullantmm** [comment]
Thanks @karter16! I just tried but looks like that URI is not available... Anyway it might mean we are getting closer!!

**Comment by karter16** [comment]
> Thanks @karter16! I just tried but looks like that URI is not available... Anyway it might mean we are getting closer!!

Interesting - so if you try to go to the URI (https://gateway-mg-au.soimt.com/api.app/v1/) from your browser what do you get? I get a `{"code":6,"message":"The service is not available,please try again later."}` response, which means that the API exists and is responding. If I use the latest version of "saic-python-client-ng" I'm able to use my iSmart username and password to connect to and control the vehicle - I have this working now.

**Comment by bullantmm** [comment]
> > Thanks @karter16! I just tried but looks like that URI is not available... Anyway it might mean we are getting closer!!
> 
> Interesting - so if you try to go to the URI (https://gateway-mg-au.soimt.com/api.app/v1/) from your browser what do you get? I get a `{"code":6,"message":"The service is not available,please try again later."}` response, which means that the API exists and is responding. If I use the latest version of "saic-python-client-ng" and specify that URI I'm able to use my iSmart username and password to connect to and control the vehicle - I have this working now.

I gave it some more work and now it works... Just had to spend some time ensuring the variables were correct. Thanks for the notifying about the updated address!

**Comment by hamishfagg** [comment]
Tried this and it doesn't seem to work in NZ. I get the 'service not available' at that endpoint, but when the gateway tried to log in it gets an "incorrect password" response (it's definitely the correct password).

@karter16 how did you find that endpoint? I might need to capture my phone's traffic

**Comment by karter16** [comment]
Hi @hamishfagg - fyi I am NZ-based so don't think it's a NZ vs AU thing.

I believe that there is a separate known issue/limitation (here it is: https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/issues/255) that your password can't contain special characters (needs to be only alpha-numeric) could it be that?

**Comment by hamishfagg** [comment]
My password is alpha-numeric, but you gave me an idea - turns out the app just ignores anything after the first 16 characters in your password (yay, security).

So, I just needed to set the env var to the first 16 chars of my password and now it's working! Thanks!

**Comment by nanomad** [comment]
Can you guys confirm it works for AU and NZ then? I'd love for you to update the README if so with the right settings to use

**Comment by bullantmm** [comment]
> Can you guys confirm it works for AU and NZ then? I'd love for you to update the README if so with the right settings to use

Definitely working for me in AU using 

SAIC_REST_URI: https://gateway-mg-au.soimt.com/api.app/v1/
SAIC_REGION: au

**Comment by karter16** [comment]
So that's confirmed - works in both AU and NZ using:

SAIC_REST_URI: https://gateway-mg-au.soimt.com/api.app/v1/
SAIC_REGION: au

**Comment by thiagofigueiro** [comment]
Amazing news because version `0.4.6` just started throwing errors for me:

```
saic-mqtt-gateway  | 2025-04-01 02:29:47,350 [  INFO  ] Updating charging status - __main__
saic-mqtt-gateway  | 2025-04-01 02:31:19,093 [ ERROR  ] handle_vehicle loop failed during SAIC API call - __main__
saic-mqtt-gateway  | Traceback (most recent call last):
saic-mqtt-gateway  |   File "/usr/src/app/./mqtt_gateway.py", line 91, in handle_vehicle
saic-mqtt-gateway  |     charge_status = self.update_charge_status()
saic-mqtt-gateway  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway  |   File "/usr/src/app/./mqtt_gateway.py", line 118, in update_charge_status
saic-mqtt-gateway  |     chrg_mgmt_data_rsp_msg = self.saic_api.get_charging_status_with_retry(self.vin_info)
saic-mqtt-gateway  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway  |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 566, in get_charging_status_with_retry
saic-mqtt-gateway  |     return self.handle_retry(self.get_charging_status, vin_info)
saic-mqtt-gateway  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway  |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 457, in handle_retry
saic-mqtt-gateway  |     return self.__handle_retry_with_app_data(func, vin_info=vin_info, max_retries=max_retries)
saic-mqtt-gateway  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway  |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 499, in __handle_retry_with_app_data
saic-mqtt-gateway  |     raise SaicApiException(f'API request failed after {iteration} retries{additional_info}')
saic-mqtt-gateway  | saic_ismart_client.exceptions.SaicApiException: API request failed after 4 retries, error message: The remote control instruction failed, please try again later.
```
