### ISSUE TITLE
Error password incorrect even tho im using the correct password.

### ISSUE THREAD

**Issue by DarrenSanders123** [SAIC-iSmart-API/saic-python-mqtt-gateway#17]
I keep getting:
`023-05-21 16:24:09,293 return code: 15019, message: Incorrect password. You may have another 3 attempts of the day，please try again.
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 427, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 113, in login
    raise SaicApiException(login_response_message.body.error_message.decode(),
saic_ismart_client.saic_api.SaicApiException: return code: 15019, message: Incorrect password. You may have another 3 attempts of the day，please try again.
return code: 15019, message: Incorrect password. You may have another 3 attempts of the day，please try again.`

I know for sure the password is correct.

**Comment by InfectedSoap** [comment]
I had the same problem but got it working by fixing the bellow two issues with my account. 

- First thing, make sure your iSMART account is created with an email address, not a phone number. 

Not sure why phone numbers can’t be used but I’m sure the developers have a good reason. 

- Second thing, remove any special characters like dashes, dots, exclamation marks, etc from the password. 

The iSMART app only support letters and numbers. If you enter any special characters in the app, it simply ignores them. If you look carefully while entering your password you’ll notice that the amounts of dots obscuring the password does not increase while entering special characters.

**Comment by DarrenSanders123** [comment]
Well that fixed it.
