### ISSUE TITLE
Gateway charging refresh period - First Value is too high

### ISSUE THREAD

**Issue by Tonno87** [SAIC-iSmart-API/saic-python-mqtt-gateway#170]
Hi, 

please take a look at this:

![Screenshot 2024-02-18 10 58 49](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/f2fb9af7-5dd2-49a0-94b5-719bbd7833fa)

The first value of the refresh period is too high:

The first charge starts @ 06:00:25 with 36,7% soc @ 06:00:28, next soc value @ 06:17:01. The gateway calculates a refresh of 975s, next value is 185s.

The second charge starts @ 08:24.45 with 56,5% soc @ 08:24:48, next soc value @ 08:48:53. The gateway calculates a refresh of 1428, next value is 187s.

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/25f8f87a-144d-4ae4-9d1f-d179fb942144)

**Comment by nanomad** [comment]
Uhm, I think we should probably let the "charging" power stabilise then. Can you post the drivetrain power chart as well?

**Comment by Tonno87** [comment]
Another day with the power values:
![Screenshot 2024-03-03 21 51 19](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/ac2cffcc-ae5f-49ba-b493-8d9bd857d378)
![Screenshot 2024-03-03 21 51 35](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/79f804d5-dfdc-4ac5-be5b-f8c68c6496d3)
![Screenshot 2024-03-03 21 51 50](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/20ff92ea-1720-405c-8957-2a663be027b5)

**Comment by nanomad** [comment]
Actually, @Tonno87 i think it's easier if you export the CSV data of the following (HA has the export finally)
- SoC%
- Drivetrain power
- Charging refresh period
- Remaining charging time
- Target SoC
- Scheduled Charging Mode

**Comment by Tonno87** [comment]
Okay, I will export it this evening. One hint: it's not possible to change the target SoC on my MG5 SR Luxury, it's always 100% on LFC battery.
Target charging is done by evcc. Do you need those sensors too?

**Comment by Tonno87** [comment]
[HomeAssistant.csv](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/files/14484541/HomeAssistant.csv)

Hope this helps. My MG5 SR Luxury can't use the TargetSoc function, so it's always disabled. I'm using EVCC instead.

**Comment by nanomad** [comment]
Thanks, I'll look at those tonight

**Comment by nanomad** [comment]
@Tonno87 Feel free to try the new RC, I've reworked the refresh interval computation to avoid using values close to 0

**Comment by Tonno87** [comment]
Thanks, i will test it tomorrow.

**Comment by Tonno87** [comment]
Seems to work now:

![Screenshot 2024-03-10 11 07 06](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/f09b36fc-c92e-4bcf-8a24-ce50c4d6be4f)

Good work!
