### ISSUE TITLE
No possible way to set temperatur in home assitant

### ISSUE THREAD

**Issue by kasper-leFevre** [SAIC-iSmart-API/saic-python-mqtt-gateway#171]
Hey,

First of all thank you a lot for the work you are putting into this project!

I'm able to get a lot of information and configure some parameters for my Marvel R, but I don't have any possible way to set the temperature for A/C only turn it on and off.

**Comment by billouetaudrey** [comment]
Hello, same issue with domoticz

"Error sending switch command, check device/hardware (idx=95) !"

Logs : 

2024-02-25 11:41:18.593 Error: MQTT Disovery: climate device unhandled mode_state_template (***_vehicle_climate/MG Marvel R (Climatisation))

**Comment by fgsch** [comment]
Same here for my MG4.

**Comment by nanomad** [comment]
Please try 0.6.0-rc2

**Comment by fgsch** [comment]
@nanomad Shouldn't this be:

```
        if self.__remote_ac_temp is not None:
            self.set_ac_temperature(self.__remote_ac_temp)
```

**Comment by kasper-leFevre** [comment]
I actually manage to solve it before I updated to 0.6.0-rc2 by adding the following to the state attribute under developer tools -> state->find the climate entiti (climate.lsjeXXXXXXXXXXX_vehicle_climate):
`temperature: 25`
that made I possible to change what temp the is set when set the HVAC mode to auto

**Comment by kasper-leFevre** [comment]
i tried deleting the state attribute updating the gateway and it now configured again. so looks like I solved it

**Comment by fgsch** [comment]
I also tried the prerelease version and it's working as expected now. Thank you!
