### ISSUE TITLE
Can't enable climate in domoticz

### ISSUE THREAD

**Issue by billouetaudrey** [SAIC-iSmart-API/saic-python-mqtt-gateway#174]
Hello, on domoticz, I can set temperature but can't activate clim ( Marvel R )

"Error sending switch command, check device/hardware (idx=95) !"

Logs :

2024-02-25 11:41:18.593 Error: MQTT Disovery: climate device unhandled mode_state_template (***_vehicle_climate/MG Marvel R (Climatisation))

**Comment by nanomad** [comment]
Is the log from domoticz? Or the python gateway?

I'm not a domoticz so I cannot help too much

**Comment by nanomad** [comment]
Seems like domoticz doesn't support value templates in YAML format, but still honors the home-assistant auto configuration messages.

I'd suggest rasing a ticket to domoticz

**Comment by billouetaudrey** [comment]
> Seems like domoticz doesn't support value templates in YAML format, but still honors the home-assistant auto configuration messages.
> 
> I'd suggest rasing a ticket to domoticz
> 
> Here's the auto-configuration message sent to the relevant topic
> 
> ```
> {
>   "name": "Vehicle climate",
>   "device": {
>     "name": "MG MG4 Electric <VIN>",
>     "manufacturer": "MG",
>     "model": "MG4 Electric 2022 BLACK PEARL",
>     "hw_version": "EH32 S",
>     "identifiers": [
>       "<VIN>"
>     ]
>   },
>   "unique_id": "<VIN>_vehicle_climate",
>   "object_id": "<VIN>_vehicle_climate",
>   "availability": [
>     {
>       "topic": "saic/_internal/lwt",
>       "payload_available": "online",
>       "payload_not_available": "offline"
>     },
>     {
>       "topic": "saic/<EMAIL>/vehicles/<VIN>/available",
>       "payload_available": "online",
>       "payload_not_available": "offline"
>     }
>   ],
>   "availability_mode": "all",
>   "precision": 1.0,
>   "temperature_unit": "C",
>   "mode_state_topic": "saic/<EMAIL>/vehicles/<VIN>/climate/remoteClimateState",
>   "mode_command_topic": "saic/<EMAIL>/vehicles/<VIN>/climate/remoteClimateState/set",
>   "mode_state_template": "{% if value == \"on\" %}auto{% else %}off{% endif %}",
>   "mode_command_template": "{% if value == \"auto\" %}on{% else %}off{% endif %}",
>   "modes": [
>     "off",
>     "auto"
>   ],
>   "current_temperature_topic": "saic/<EMAIL>/vehicles/<VIN>/climate/interiorTemperature",
>   "current_temperature_template": "{{ value }}",
>   "temperature_command_topic": "saic/<EMAIL>/vehicles/<VIN>/climate/remoteTemperature/set",
>   "temperature_command_template": "{{ value | int }}",
>   "temperature_state_topic": "saic/<EMAIL>/vehicles/<VIN>/climate/remoteTemperature",
>   "temperature_state_template": "{{ value | int }}",
>   "min_temp": 17,
>   "max_temp": 33
> }
> ```

Lemme try with home assistant ;) thanks

**Comment by billouetaudrey** [comment]
Confirmed, work with home assistant, sorry for disturb
