### ISSUE TITLE
Releasing: Changelog and main branch

### ISSUE THREAD

**Issue by malys** [SAIC-iSmart-API/saic-python-mqtt-gateway#179]
Thanks for your work!

Last releases were not correctly packaged.

For every release (stable tags), could you everytime:
- move main branch
- update changelog (currently is out to date 0.5.10 -> 0.5.15)

Many Thanks!

**Comment by nanomad** [comment]
Sure thing. Now main tracks 0.5.15.
I'll update the changelog
