### ISSUE TITLE
No more range since last update 

### ISSUE THREAD

**Issue by an0Nym0us63** [SAIC-iSmart-API/saic-python-mqtt-gateway#180]
Since the update of my docker yesterday (rc4)

Range is 0km

If i revert back to 0.5.15 i get back the range

My car is an MG4 Luxury

Regards

Edit : same thing on my Friends install with a ZS EV so it doesnt seem car related

**Comment by nanomad** [comment]
> It seems that once the car as been started once range is coming back

That's correct. The idea of the RC was to test out that theory. Indeed we should  get the electric range from the BMS and not the  car state as car state gets reset while the car is parked

I'll work on addressing that

**Comment by nanomad** [comment]
@an0Nym0us63 Please try 0.6.0-rc5

Also: It's not a good idea to track the pre-release line as, as you saw, it may contain bugs

**Comment by an0Nym0us63** [comment]
I will test that tomorrow.

Its not a problem, im willing to test and report. So i that there Can be bugs.

Its easy for me to juste change the release tag if i need to revert black.

But some of us has to sometimes test pre releases to make some feedbacks ;)

**Comment by an0Nym0us63** [comment]
@nanomad 

Confirmed working After testing rc5
