### ISSUE TITLE
[QUESTION] How to get the charging power

### ISSUE THREAD

**Issue by fgsch** [SAIC-iSmart-API/saic-python-mqtt-gateway#184]
Hi. Is there any topic for the charging power? Is it drivetrain/power? If so, why is it showing as -X.XXX?

**Comment by nanomad** [comment]
It's the realtime reading of the power being supplied by the BMS
- Negative values: power is being fed into the battery (charging or regen braking)
- Positive values: power is being used (AC, heater, just driving around).

If you are interested in just the "power during charging" I suggest you look at that value while the isCharging topic reports true or while the charger plug is connected

**Comment by fgsch** [comment]
Great, thank you!
