### ISSUE TITLE
Discussion: should HA show "Unavailable" for entities whenever we fail to poll the SAIC API?

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#186]
As title says, I'd like to gather some feedback about the current behaviour and a possibile change:
- Currently HA entities show "available" as long as the docker container of the MQTT Gateway is alive

But sometimes we fail to talk with the SAIC API (either for a specific car or completely), giving HA false information about the data (i.e. if you use an utility meter integration to compute the kWh charged)

The proposal (testable with this `docker image: ghcr.io/nanomad/saic-python-mqtt-gateway/saic-mqtt-gateway:0.6.0-rc8`) is to make:
- Gateway configuration entities available as long as the gateway docker container is connected to MQTT (mostly refresh mode and refresh periods)
- Car entities available as long as we managed to poll BOTH car state and battery state

What do you think?

**Comment by nanomad** [comment]
Tagging @tisoft @magior @Tonno87 @tosate for feedback :)

**Comment by cybersmart-eu** [comment]
I like this idea. In my case with two cars Inregularily experience that one car peovides. data and at the same time the other car shows an error and no dara can be requested anymore (sometimes for days). So while MQTT GW and also SAIC API login are successfull, data from one car is not available/reliable anymore.

**Comment by nanomad** [comment]
> However as I am not using HA the sams information should be provided via MQTT in a dedicated topic for other SmartHome systems to fetch the status per car.

It will be :) 
I've added a new topic under the car info with the usual 'online' and 'offline' payloads

**Comment by Tonno87** [comment]
As a technician i would say: Better no values than wrong values! From this point of view it's a good idea.
Additionally in the case of problems we can better specify if it's a gateway or api problem. 

On the other hand this behaviour will provoke more issues and discussions.

**Comment by nanomad** [comment]
> On the other hand this behaviour will provoke more issues and discussions.

To be fair, I've already had my fair share of discussion about "commands not working"

Keep in mind the proposal only applies to "polling" errors so essentially mostly during driving and as a response to a successful command execution.

The question now is...how can we make users aware of errors during commands execution? I bet that is a more common scenario, and I don't think putting the whole car into an "unavailable" state is the best choice in terms of user experience

**Comment by Tonno87** [comment]
To understand the changes in RC8 without testing your image yet:

If the gateway polls any values without success  all car entity's became unavailable like this:

![Screenshot_20240312-011645.png](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/66f88080-f976-4e50-9169-c56020957daa)


What do you think about sending a notification to home assistant if a command doesn't work?

![Screenshot_20240312-014542.png](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/b3ed5a85-6bd2-41eb-bb9f-0562931aa98d)

**Comment by Tonno87** [comment]
Is it possible to create an automation with autodiscovery? If so we can trigger the notification service by sending an mqtt message to home assistant.

A native Integration is a cool idea, but if we change something we need to wait for home assistant updates... Or we need to release it at the Hacs store.

**Comment by nanomad** [comment]
> Is it possible to create an automation with autodiscovery? If so we can trigger the notification service by sending an mqtt message to home assistant.

Unfortunately not :(
We can use HA API keys and API call to  `http://<HA_URI>:8123/api/services/notify` though

**Comment by tosate** [comment]
I also like the idea of setting entities to unavailable if we did not manage to get proper values. This should improve the statistics for certain sensors.
I would use notifications in very specific scenarios only. From my point of view it makes sense when a user invokes a command so that he receives a feedback in case of error and does not need to look into the log.
For polling errors I would avoid the notifications because they can quickly pile up and annoy the user.

**Comment by Tonno87** [comment]
Installed the new pre-release at 19:27:49, everything seems to work. but at 20:57:41 the car became unavailable. Seems that the gateway failed with "code 4: the remote control instruction failed, please try again later. "
![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/d5f5065d-309a-42cf-b6a6-28b83d287133)

**Comment by Tonno87** [comment]
Seems that the car won't go to a sleep state:

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/2faeba5b-4d4e-4359-93ca-caecc3a80300)

**Comment by nanomad** [comment]
> Seems that the car won't go to a sleep state:
Interesting, I don't think I changed the refresh logic there. Let me check

**Comment by nanomad** [comment]
Ah you're right... I think it's just an edge case that has always been there but we failed to notice in the past....
It may happen that we fetch the car state but not the charge state. If so, the gateway gets stuck in a loop never marking the refresh as successful

**Comment by Tonno87** [comment]
Seems that the charging state doesn't work at the moment, but the car state does:

![Screenshot_20240313-220449](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/3d1cf310-c801-48b0-8f3e-b5d99506d332)
![Screenshot_20240313-220539](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/1efe77aa-9681-470a-8dc2-01ab9d87ce5d)

Logfiles are not so easy in home assistant... no idea where to find them outside the addon console

**Comment by nanomad** [comment]
> Seems that the charging state doesn't work at the moment, but the car state does:
> 
> Logfiles are not so easy in home assistant... no idea where to find them outside the addon console

No worries, I'll have an hotfix shortly. For now it will mark the refresh as successfull, I'll work on having different availabilities depending on the provenance of the data

**Comment by nanomad** [comment]
@Tonno87 please try RC10. If it works I kindly ask you to push it as an add-on update

**Comment by Tonno87** [comment]
![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/0db00022-1690-482b-a5cd-f3a25e5bd7a0)

Seems to work. RC10 is already pushed to the pre addon.
