### ISSUE TITLE
detect car is charging 

### ISSUE THREAD

**Issue by lorddoener** [SAIC-iSmart-API/saic-python-mqtt-gateway#20]
First of all: After a test over several weeks, the latest version 0.21 for the MG4 Luxury runs absolutely stable. No reboot needed.

However, if there is no openWB or the electric car is charged on the road: What are the possibilities to detect this and retrieve the values more regularly ? The charge status is queried by default only once a day.

In the Develop branch I have seen that in the future there should be an update when the doors are opened and closed. This could solve the problem if the charging process was started before closing, correct?

**Comment by dudelburg** [comment]
I would suggest to keep polling the car state with the active delay (30 seconds by default) for some time after the car goes to the "inactive" state. In most cases, charging will start soon after the car was stopped (at least in my case).

**Comment by tisoft** [comment]
Just for reference, that is also the way the Java implementation does it. It keeps polling for 10 Minutes after engine stop. In the main branch we also made this configurable with the `refresh/period/inActiveGrace/set` topic (See  https://github.com/orgs/SAIC-iSmart-API/discussions/6#discussioncomment-5923522 for discussion)

**Comment by nanomad** [comment]
That sounds amazing. I'd love if the inactive grace refresh period could be configured to be different from the active refresh interval as I've seen the battery voltage drop quite a bit during polling when the car Is off.
