### ISSUE TITLE
How to get the ABRP user token ?

### ISSUE THREAD

**Issue by Chuckame** [SAIC-iSmart-API/saic-python-mqtt-gateway#203]
Hello,

I'm unable to get or generate the user token following the following from iternio: https://github.com/iternio/ovms-link?tab=readme-ov-file#obtain-live-data-token (no Live Data button as explained).

The goal here is to fill the env var `ABRP_USER_TOKEN`.

How to get this token ?

**Comment by cybersmart-eu** [comment]
You might need to request it by Email from ABRP team for your account. I sent an Email to contact@iternio.com with my Login email address and they provided me with the Key.

**Comment by kasper-leFevre** [comment]
you can fetch a token yourself from under your car configuration go to live data from the car and fetch a generic token

**Comment by Chuckame** [comment]
I don't this live data button :/

**Comment by nanomad** [comment]
@Chuckame if you are using an OBD dongle, you need to de-configure it first.

You can always re-add it later after you get the car token
