### ISSUE TITLE
Heading unit of measurement

### ISSUE THREAD

**Issue by bj00rn** [SAIC-iSmart-API/saic-python-mqtt-gateway#227]
Heading has no unit of measurement and values are interpreted as strings.

Suggestion: change to degrees 

![Screenshot_20240419-171415](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/10961167/e6d49897-6318-4bca-9387-abb991f4bbde)

**Comment by nanomad** [comment]
Nice catch :)

**Comment by nanomad** [comment]
Fix scheduled for 0.6.1-rc5
