### ISSUE TITLE
Latest tag on docker hub

### ISSUE THREAD

**Issue by bluediamond1984** [SAIC-iSmart-API/saic-python-mqtt-gateway#232]
On docker hub, every developer release is also tagged as `latest`. I think it's unintentional on building the image. I would expect that only the stable version should be tagged with `latest`.

**Comment by nanomad** [comment]
Fixed in https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/commit/96624d4279f6f8f6a94d692232157e98289740c0

Thanks for bringing this up, we will now publish latest only on stable releases while dev will be used to track the latest rc
