### ISSUE TITLE
Vehicle start missed due to clock skew on SAIC servers

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#24]
Last week had the gateway not switch into "car running" mode due to the following scenario:
- Car was started at 10:15
- Car was stopped at 10:20
- Car was restarted at 10:25

The issue is that the SAIC SMS message timestamp was skewed quite a bit so the timestamps, from SAIC point of view, were as follows:
- Engine Start at 10:00
- Engine Start at 10:10

Given the second engine start timestamp (wrong) was after the timestamp (correct) that the gateway used to decide that car was off (last_car_activity) the gateway then skipped it and we missed all the driving data for that session.

A quick fix I made is to make the function force_update_by_message_time always return True. 

This should be fine since we actually ignore SMS messages in the past by comparing their respective timestamps (which, while wrong, should be consistent with each other)

**Comment by tosate** [comment]
Hi @nanomad 

my car has an issue with the TPMS sensors that provide the tire pressure. Whenever I start the car, there are 4 alarm messages. Since they are not deleted, they are received every minute with the message polling.
I fear that your change would always force a refresh in my case.

**Comment by nanomad** [comment]
Hi @tosate yeah I see that. Question though, why are they not deleted? With my tests I saw an increase in processing time if I keep old messages lying around. I'd rather publish them on MQTT for later retrieval / archival.

Another option (that I'm currently working on) is to refresh only on every vehicle start message instead of every message. That should fix both your issue and mine

**Comment by tosate** [comment]
Hi @nanomad I wanted to keep the alarms in case there would be something remarkable. The vehicle start messages are immediately deleted. Basically, I don't notice them. Publishing on MQTT means that you would only have the latest message, right? Probably another application would be needed to archive them.
I am currently working on a larger refactoring to tidy-up the code. Similar to the structure of the Java implementation.

**Comment by nanomad** [comment]
I'll close this for now as the new implementation seems quite robust on this topic. I'll re-open it if it happens again
