### ISSUE TITLE
Acknowledge messages to reduce log spam

### ISSUE THREAD

**Issue by fschwarz86** [SAIC-iSmart-API/saic-python-mqtt-gateway#244]
Hi there,

first of all: Thanks for providing this gateway, amazing work! :)

I've witnessed significant log spam due to not acknowledged messages:

`2024-05-20 13:55:19,643 [  INFO  ] ID: 35824xxx, Time: 2024-04-27 14:01:05, Type: 802, Title: Warnung vor unerlaubtem Eindringen, Content: Ein ungewöhnliches Eindringen in Ihr Fahrzeug (***xxx) hat am 27-04-2024 14:01:04 GMT+02:00 einen Alarm ausgelöst.-MG Motor, Status: unread, Sender: TBOX, VIN: XXXXXXXXXXXX - __main__`

Would it be possible to set those messages to "read"?

Best,
Florian

**Comment by nanomad** [comment]
Hi Florian,

Could you check with the latest 0.6.2-rc13? It should have been addressed already

**Comment by fschwarz86** [comment]
I have updated to 0.6.2 yesterday and this seems to be fixed. Thank you!
