### ISSUE TITLE
refresh of range

### ISSUE THREAD

**Issue by mrniemand** [SAIC-iSmart-API/saic-python-mqtt-gateway#25]
can someone describe when range is refreshed? 
.*:saic/leader\x40simplesign\x2ede/vehicles/LSJWH4091PN090151/drivetrain/range
I don't get the concept. In my house automation I want to create an reading, which shows the range of the MG4
It looks as when it's refreshed while charging but not when driving

**Comment by nanomad** [comment]
I'm using the MQTT topic drivetrain/range myself. Seems to be updated just fine while driving (MG4 LUX):

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/1129926/07e62b82-3e89-48b3-89f1-839200562e7c)

**Comment by mrniemand** [comment]
and how long after stopping?
