### ISSUE TITLE
Docker - Update Error

### ISSUE THREAD

**Issue by dandwhelan** [SAIC-iSmart-API/saic-python-mqtt-gateway#250]
Hi, I've recently installed saic-phython-mqtt-gateway on docker. It was working for 12 hours until I restarted my docker pi this morning.  As you can see from the logs, it does speak to saic at the beginning and then keeps erroring (attached). Any suggestions welcome on how I can fix this... Or is it a bug?

[saic-mqtt-gateway-2024-07-07T20-11-47.log](https://github.com/user-attachments/files/16120646/saic-mqtt-gateway-2024-07-07T20-11-47.log)

**Comment by tosate** [comment]
Hi @dandwhelan 

this behavior is well known. There is a limited number of requests per day, maybe you hit this boundary somehow.

From my experience the only way to get out of the message...

```
return code: 4, message: The remote control instruction failed, please try again later.
```

... is to turn on the car.

Just turn on the gateway after your next drive. Then it should be okay again.

**Comment by skipperkm** [comment]
I have the same problem. How many requests per day are allowed? Is the interval of 60s perhaps too short?

**Comment by nanomad** [comment]
Unfortunately we don't really know what the cap is, you can definitely increase the polling rate and see if that helps. It seems like the cap has a monthly reset, but that's just empirical evidence.
