### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by Ranzengar** [SAIC-iSmart-API/saic-python-mqtt-gateway#255]
Hi, i'm trying to access with the same credentials that are working on the official mg ismart app but for some reason i'm getting "wrong password" error message. 
Has happened to somebody? I'm providing the password in clear, should i encrypt it in some way?

**Comment by tosate** [comment]
Hi @Ranzengar 

you provide the password in clear text as an argument or in an environment variable. The [SHA-1](https://en.wikipedia.org/wiki/SHA-1) of your password is sent in the login request.

On your MQTT broker you can find the topic `saic/_internal/api/oauth/token/request` that shows you the actual login request that has been sent to the SAIC API. The body starts with `grant_type=password&username=<your-user>&password=<your-hashed-password>`.

You can validate the password hash value in Bash:
```
echo -n "your-password" | sha1sum
```

This command will show you the value of your password and it should match with the value in the request.

**Comment by nanomad** [comment]
Looks like there's a limitation on password length as well. Max 16 characters
