### ISSUE TITLE
/refresh/mode/set. wrong type

### ISSUE THREAD

**Issue by JohGrei** [SAIC-iSmart-API/saic-python-mqtt-gateway#256]
Always when I try to set the value of the State `/refresh/mode/set` to one of the following states `(periodic/off/force)`, I get this error.

`You are assigning a string to the state "mqtt.0.saic.xxxxxxxxxx.refresh.mode.set" which expects a number.`

Anyone know which numeric values are for the 3 states

**Comment by tosate** [comment]
Hi @JohGrei 

try with:

- FORCE: 1
- OFF: 2
- PERIODIC: 3

Whatever you are doing there, more context would help.

![Screenshot from 2024-08-19 19-22-40](https://github.com/user-attachments/assets/c1289d59-c20e-490b-bfb6-8186642bc1e2)

The mode is a string value on the MQTT Broker.

In Python you could re-use the [RefreshMode Enum](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/blob/main/vehicle.py).

**Comment by JohGrei** [comment]
Thanks for the reply, i changed the Type in ioBroker to string and now it works without any problems.
