### ISSUE TITLE
0.6.3 - Unsupported Operand for *, issue with Type

### ISSUE THREAD

**Issue by ZionFox** [SAIC-iSmart-API/saic-python-mqtt-gateway#259]
Since updating to 0.6.3 Release, I've been getting an exception thrown when the gateway is attempting to talk to the car. Seems it's not working out the battery capacity due to probably being unable to get data from the car, and because the variable doesn't have a Type, it throws this exception when being used as an operand during multiplication.

Here's the stack trace:
```
2024-09-27 18:32:49,125 [ ERROR  ] Error updating charge status - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 99, in handle_vehicle
    charge_status = await self.update_charge_status()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/./mqtt_gateway.py", line 153, in update_charge_status
    self.vehicle_state.handle_charge_status(charge_mgmt_data)
  File "/usr/src/app/vehicle.py", line 812, in handle_charge_status
    time_for_1pct = 36.0 * self.get_actual_battery_capacity() / abs(charge_mgmt_data.decoded_power)
                    ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

Might be wise to look into why this could be happening, and having default values or fixed types for null values.

**Comment by nanomad** [comment]
@ZionFox feel free to try 0.7.0-rc2 as that should fix this issue.

Let me know if you can run docker or if you need an home assistant addon release

**Comment by ZionFox** [comment]
I pulled the 0.7.0-rc2 docker image and can confirm it's not throwing this exception any more. Thank you!
