### ISSUE TITLE
Using docker-compose.yml, but container does not start

### ISSUE THREAD

**Issue by gellfuen** [SAIC-iSmart-API/saic-python-mqtt-gateway#270]
Hello!
I've already done a few things with Docker and Docker-compose files and can use them. However, I don't understand how the gateway is supposed to work with your docker-compose file, or I haven't found the corresponding instructions!

My docker-compose file: 

services:
  saic-mqtt-gateway:
    image: ‘saicismartapi/saic-python-mqtt-gateway:latest’
    container_name: ‘saic-mqtt-gateway’
    environment:
      - MQTT_URI=tcp://192.168.1.2:1883
      - MQTT_USER=username
      - MQTT_PASSWORD=password
      - SAIC_USER=mail.address@mail.com
      - SAIC_PASSWORD=saicpassword
      - LOG_LEVEL=DEBUG
      - MQTT_LOG_LEVEL=DEBUG
    volumes:
      - ./app:/usr/src/app

Docker can create the conatiner, but terminates it immediately with the error:
saic-mqtt-gateway | python: can't open file ‘/usr/src/app/./mqtt_gateway.py’: [Errno 2] No such file or directory

THX for help!
regards

**Comment by nanomad** [comment]
You shouldn't mount the app folder, remove the volumes definition and it
should start fine

Il Dom 20 Ott 2024, 14:18 gellfuen ***@***.***> ha scritto:

**Comment by gellfuen** [comment]
Hello Giovanni,

I removed the volumes definition and it works now.
THX
regards



Am So., 20. Okt. 2024 um 16:54 Uhr schrieb Giovanni Condello <
***@***.***>:
