### ISSUE TITLE
Question: Is there a option to turn on steering_wheel Heating?

### ISSUE THREAD

**Issue by michpas** [SAIC-iSmart-API/saic-python-mqtt-gateway#273]
I found Heated Seat Front Left & Right that can be set remotely.
Is there also an option to set the steering Wheel heating on via this Gateway? 
In the App there is an option to select.

**Comment by nanomad** [comment]
Are you sure you can in the app? On my MG4 I cannot

![image](https://github.com/user-attachments/assets/796794ea-f689-44e0-bfe7-4888bdc7735a)

**Comment by michpas** [comment]
You are right. I must have been mistaken. I double checked and also can't find it in the app. Will close this item.
