### ISSUE TITLE
Unable to turn remote climate on while car is charging

### ISSUE THREAD

**Issue by credulous67** [SAIC-iSmart-API/saic-python-mqtt-gateway#275]
I have recently noticed, now that it is getting cold again, that if I try to turn climate or front demister on remotely while the car is charging it will fail (see screenshot of logs)
![Screenshot_20241120-024247](https://github.com/user-attachments/assets/f287ed51-f4ae-4fde-a571-c6c2a74f4f1c)

As soon as the charge finishes then you can turn it on without issues. Is this a quirky creature of my MG5, or is this a gateway problem?

**Comment by nanomad** [comment]
This is a known issue on some MG models due to the interaction between the gateway, tbox and the CCU. On some models (MG4) it is possibile to get a module upgrade that fixes issues like this
