### ISSUE TITLE
Feature: Energy Usage of Journey

### ISSUE THREAD

**Issue by dml33** [SAIC-iSmart-API/saic-python-mqtt-gateway#277]
Hello.

I have been using this addon for a week and it's great. It shows lots of parameters of the car 👍 

I would like to request a sensor which could provide the energy used in the journey. There are already sensors with the Energy Usage of the Day and Energy Usage since Last Charge, Mileage of Journey, but not the Energy Used of Journey.

Please, if it possible, provide it.

Thanks!

**Comment by nanomad** [comment]
Unfortuntaly those are not stored by the API so we cannot implement directly. 
It is also tricky to compute those from e.g. the step integral function of the power (W) used by the car due to the poor temporal resolution of the data.
