### ISSUE TITLE
Car without mobile reception -> inconsistencies in mileage, energy usage, etc

### ISSUE THREAD

**Issue by dml33** [SAIC-iSmart-API/saic-python-mqtt-gateway#278]
Hi.

This morning, I took the car to my job. I parked it in a parking underground without mobile reception. Later, I left, and at home, I have checked the statistics. It seems that that period without signal made a little mess with statistics.

From 9:40 till 14:10, the car was without reception. The car was not being charged. 

![image](https://github.com/user-attachments/assets/f2d25241-0a5e-4fc7-8f02-5cc3389560e1)

It seems like the daily counters had been reset somehow.

Mileage of the journey and the day are the same:
![image](https://github.com/user-attachments/assets/4b14b7b2-b0c0-484c-bee9-4409b343b2e4)

![image](https://github.com/user-attachments/assets/e022e34f-a9ee-470c-85a3-7e318cd7b6f8)

The energy used since last charge and of the day have been reset somehow:
![image](https://github.com/user-attachments/assets/903e8d21-0e51-45ba-9646-77e4ee083b7b)

![image](https://github.com/user-attachments/assets/7cd6fc6d-d590-47a9-9837-82e7f78c044b)

SoC kWh is ok:
![image](https://github.com/user-attachments/assets/4cd06fad-307d-49c1-8288-dcd71e6569b6)

Last charge SoC is not ok:
![image](https://github.com/user-attachments/assets/90db1c8b-b818-425c-81c1-0340a109f283)

Battery was not charged:
![image](https://github.com/user-attachments/assets/f5d8c475-80e8-4e60-9bc7-ac44110e145f)

Any clues?

Thanks!

**Comment by nanomad** [comment]
Yeah, the on board computer is stupid and resets those stats randomly sometimes (even when it glitches out and looses communication with other ECUs).

Nothing that we can do here :(
