### ISSUE TITLE
v0.7.0-rc7->rc9 - Unsupported Topic when attempting to publish changes to the gateway.

### ISSUE THREAD

**Issue by ZionFox** [SAIC-iSmart-API/saic-python-mqtt-gateway#279]
Attempted to change settings in the car (locking the doors) and gateway (changing afterShutdown interval) after pulling the latest release candidate, rc9.

```
2024-12-10 09:51:58,452 [ ERROR  ] Unsupported topic zion[****]@gmail.com/vehicles/LSJW[****]2049/doors/locked/set - handlers.vehicle
Traceback (most recent call last):
  File "/usr/src/app/handlers/vehicle.py", line 437, in handle_mqtt_command
    await self.vehicle_state.configure_by_message(topic=topic, payload=payload)
  File "/usr/src/app/vehicle.py", line 585, in configure_by_message
    raise MqttGatewayException(f'Unsupported topic {topic}')
exceptions.MqttGatewayException: Unsupported topic zion[****]@gmail.com/vehicles/LSJW[****]2049/doors/locked/set

2024-12-10 10:15:04,732 [ ERROR  ] Unsupported topic zion[****]@gmail.com/vehicles/LSJW[****]2049/refresh/period/afterShutdown/set - handlers.vehicle
Traceback (most recent call last):
  File "/usr/src/app/handlers/vehicle.py", line 437, in handle_mqtt_command
    await self.vehicle_state.configure_by_message(topic=topic, payload=payload)
  File "/usr/src/app/vehicle.py", line 585, in configure_by_message
    raise MqttGatewayException(f'Unsupported topic {topic}')
exceptions.MqttGatewayException: Unsupported topic zion[****]@gmail.com/vehicles/LSJW[****]2049/refresh/period/afterShutdown/set
```

The issue also exists in rc8 and rc7. **The issue does not exist in rc6**, and I was able to set the `inActive` period which reflected the change immediately.

**Comment by nanomad** [comment]
Uhm, interesting, I cannot reproduce it locally with my RC9 version. I have a feeling this may be due to a configuration difference between our installations or some mixed-case in the email address or car VIN number.

The log shows that the saic prefix got removed correctly while the email + vin combo didn't.

Could you pleaase confirm that:
- email is all lowercase (both in configuration and log file)
- VIN is all uppercase

**Comment by ZionFox** [comment]
I'm the user with the + in their email address, that recently reported it was an unsupported character for MQTT topics a while ago.

The exception unredacted shows it was replaced with an underscore `_` between the characters, which is suitable escaping for MQTT. The VIN's characters are all uppercase. It might be related to the email address.

I'd be happy to test for future changes.

**Comment by nanomad** [comment]
@ZionFox indeed it's currently a bit of a mess where the email normalization happens and where it doesn't, I'll rework the code a bit to make things a bit clearer

**Comment by nanomad** [comment]
Let me know if you can try rc10 standalone or if you need me to release a new RC to HACS

**Comment by ZionFox** [comment]
I've tested the latest release candidate (12), and performing the actions that failed last time are working as expected this time. I see the change in the email character escaping during the initial topic set up for the setters, so I'm confident this has resolved the issue.

Thank you!
