### ISSUE TITLE
no matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by Tonio16** [SAIC-iSmart-API/saic-python-mqtt-gateway#28]
Hello

I want to have a docker-compose instence on my Pi3+ but if I start the installation, I have this message:
no matching manifest for linux/arm/v7 in the manifest list entries

How to go further here?

Tx

Antoine

**Comment by tosate** [comment]
Hi Antoine,

I will add the value linux/arm/v7 to the platforms parameter under docker/build-push-action@v4 in .github/workflows/build_python_mqtt_images.yml

This should do the trick.

Cheers,
tosate

**Comment by Tonio16** [comment]
Thanks

I will test asap. 

Antoine

**Comment by tosate** [comment]
A linux/arm/v7 image is now available on Docker Hub

**Comment by Tonio16** [comment]
Hello

It's working fine. I have just to understand how to set the login and password now.

Tx

Antoine
