### ISSUE TITLE
problems runnning in docker via synology socket.gaierror: [Errno -2]

### ISSUE THREAD

**Issue by klefreak** [SAIC-iSmart-API/saic-python-mqtt-gateway#30]
since update to version 2.4 (or  possibly in kombination with update of my synology nas built in Docker, now called "container manager")  got problem with using the Saic-gateway...

when i now start container, after a view seconds i get an error and container stopps.
log writes:

<html><body>

date | stream | content
-- | -- | --
2023/07/06 14:52:09 | stdout | socket.gaierror: [Errno -2] Name or service not known
2023/07/06 14:52:09 | stdout | for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2023/07/06 14:52:09 | stdout | File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
2023/07/06 14:52:09 | stdout | for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2023/07/06 14:52:09 | stdout | File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
2023/07/06 14:52:09 | stdout | return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
2023/07/06 14:52:09 | stdout | File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
2023/07/06 14:52:09 | stdout | sock = self._create_socket_connection()
2023/07/06 14:52:09 | stdout | File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1044, in reconnect
2023/07/06 14:52:09 | stdout | return self.reconnect()
2023/07/06 14:52:09 | stdout | File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
2023/07/06 14:52:09 | stdout | self.client.connect(host=self.host, port=self.port)
2023/07/06 14:52:09 | stdout | File "/usr/src/app/mqtt_publisher.py", line 41, in connect
2023/07/06 14:52:09 | stdout | self.publisher.connect()
2023/07/06 14:52:09 | stdout | File "/usr/src/app/./mqtt_gateway.py", line 379, in __init__
2023/07/06 14:52:09 | stdout | mqtt_gateway = MqttGateway(configuration)
2023/07/06 14:52:09 | stdout | File "/usr/src/app/./mqtt_gateway.py", line 719, in <module>
2023/07/06 14:52:09 | stdout | Traceback (most recent call last):

</body>
</html>

i'm a noob in these things but can follow simple steps :)

UPDATE:
rebuild a "old" 0.2.3 Container and get same error...
looks like the Updated Docker App in Synology makes the problems but can some experts translate this "Errno -2" in som enoob friendly "how to solve"  thx

**Comment by tosate** [comment]
I would say that there is a timeout problem to connect to your MQTT Broker.
`return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)`
Everything above this line comes from the Python runtime and has nothing to do with the gateway implementation.

Please validate your configuration. Especially the MQTT_URI

**Comment by klefreak** [comment]
Thank you
After rechecking All parameters, I found out that the uri was wrong because I had the TCP: parameter in double (TCP: TCP.....) Container works now ..
