### ISSUE TITLE
Question: battery target load

### ISSUE THREAD

**Issue by michpas** [SAIC-iSmart-API/saic-python-mqtt-gateway#36]
I got the gateway running and can see the basic information of various sensors (mileage, soc_kwh, soc etc). This is really great.

Having gone through all material & mttq values; I couldn't find the node/topic related to the battery target setting.
Where can I find this value?

and 2nd question, is it already possible to ''set' this value via the mttq gateway

Thanks. Love this integration

**Comment by nanomad** [comment]
See: https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/issues/35#issue-1804580155

You need an unreleased version (0.3.0 rc1) with potentially my patches to make it work a little bit better
