### ISSUE TITLE
Feature Request: Start polling before scheduled charging

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#41]
Now that the API has the decoding for the start/stop scheduled charging and for scheduled charging mode it would be nice if the gateway started polling a couple of minutes around the start of scheduled charging and if the schedule is enabled.

Note that the API has times in the local timezone of the car, so we will have to assume that the gateway is running in the same timezone

**Comment by nanomad** [comment]
> Note that the API has times in the local timezone of the car, so we will have to assume that the gateway is running in the same timezone

Looking the app, I can see a new set of REST API endpoints, including one to get the car Timezone. This should make this more reliable

**Comment by tosate** [comment]
This means that you can retrieve the scheduled charging values that have been specified in the App?
![69958CEB-55A0-442C-9796-734A921CE6C9_1_201_a](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/35031183/aaf04233-cc42-4198-86a4-08a6dd6adb4f)

And with this information you start the polling afterwards?

By the way, what is the label of the save buttons in the Italien localization?
In the German version, they have put "Retten" which means rescue instead of save.

**Comment by nanomad** [comment]
Yeah, that's correct. They are also controllable via MQTT

**Comment by tosate** [comment]
Unfortunately, I didn't test this well enough. I don't have any scheduled charging configured. In `VehicleState.update_scheduled_charging()` the mode is `ScheduledChargingMode.DISABLED` and I end-up in the else branch where it tries to remove a job. Then it crashes.

```
2023-07-31 19:23:29,749 Updating charging status
2023-07-31 19:25:06,694 Removing scheduled check for charging start for VIN XXXXXXXXXXXXXXXXXX
2023-07-31 19:27:20,133 'handle_vehicle_XXXXXXXXXXXXXXXXXX' task crashed with an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/tosate/git/saic-python-mqtt-gateway/mqtt_gateway.py", line 100, in handle_vehicle
    charge_status = self.update_charge_status()
  File "/home/tosate/git/saic-python-mqtt-gateway/mqtt_gateway.py", line 129, in update_charge_status
    self.vehicle_state.handle_charge_status(charge_mgmt_data)
  File "/home/tosate/git/saic-python-mqtt-gateway/vehicle.py", line 513, in handle_charge_status
    self.update_scheduled_charging(start_time, mode)
  File "/home/tosate/git/saic-python-mqtt-gateway/vehicle.py", line 163, in update_scheduled_charging
    self.__scheduler.remove_job(job_id)
  File "/home/tosate/git/saic-python-mqtt-gateway/venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 625, in remove_job
    raise JobLookupError(job_id)
apscheduler.jobstores.base.JobLookupError: 'No job by the id of XXXXXXXXXXXXXXXXXX_scheduled_charging was found'
2023-07-31 19:27:20,163 Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /home/tosate/git/saic-python-mqtt-gateway/mqtt_gateway.py:469> exception=SystemExit(-1)>
```

**Comment by nanomad** [comment]
> > Note that the API has times in the local timezone of the car, so we will have to assume that the gateway is running in the same timezone
> 
> Looking the app, I can see a new set of REST API endpoints, including one to get the car Timezone. This should make this more reliable

See: https://github.com/SAIC-iSmart-API/saic-python-client/pull/11

Given this is user-specific we will have to assume all cars are in the same timezone as the user, but we are decoupling it from the server's timezone (I like to run my servers in UTC but my timezone is GMT+02:00)
