### ISSUE TITLE
Changing Tire pressure with a Marvel-R

### ISSUE THREAD

**Issue by ChrisPiel70** [SAIC-iSmart-API/saic-python-mqtt-gateway#5]
Hello,

as already commented i get 4.7 reported often as Tire pressure ( iSMart App / Car shows 2.7 Bar ). Sometimes i get 3.8 as Tire pressure reported. This is reported for alle tires at the same time.

I am not sure if its related but the Marbvel-R also shows Tire Temperature. 

![image](https://user-images.githubusercontent.com/68636799/231074312-9b5d7dfe-9274-4913-b4f1-51a1cbeca37a.png)

**Comment by tosate** [comment]
I thought the tyre pressure is provided in Pounds per square inch (PSI). It's divided by 14.5 to get the bar (metric unit of pressure) value. The behavior is the same on my car. Either I get the value 0 for each tyre or something like 3.7 for each tyre.

My car sends alarm notifications for the RDKS sensors. I need to visit the garage before I can further investigate.

**Comment by ChrisPiel70** [comment]
Hello,

FYI.

today I tested the Java "saic-ismart-mqtt-gateway-0.2.0-full". This client reports other Tire pressures.

![image](https://user-images.githubusercontent.com/68636799/231714515-6d2813e2-1e54-44f6-b593-81d30763dcaa.png)

**Comment by lucky2k12** [comment]
Somewhere in the goingelectric thread c1olli stated the factor to be 25. That would also fit to my MG4
https://www.goingelectric.de/forum/viewtopic.php?p=2059202#p2059202

**Comment by tosate** [comment]
This seems to be fixed now.
