### ISSUE TITLE
Replace the openWB support with a more general approach to integrate charging stations

### ISSUE THREAD

**Issue by tosate** [SAIC-iSmart-API/saic-python-mqtt-gateway#51]
Replace the openWB support with a more general approach to integrate charging stations

- OPENWB_LP_MAP parameter becomes deprecated
- Introduce a new parameter that maps the topic for subscribing to the charge event, the value that represents charging and the topic to publish the SoC to a VIN

For an openWB charging station this would mean

- charge event topic: openWB/lp/1/boolChargeStat
- charging value: 1
- SoC topic: openWB/set/lp/1/%Soc

This allows to integrate any charging station with the gateway. This doesn't need to be part of version 0.3.0. It can be foreseen for a later release.

**Comment by tosate** [comment]
Maybe a JSON string could serve to configure this
```
[
    {
        "chargeStateTopic": "openWB/lp/1/boolChargeStat",
        "chargingValue": "1",
        "socTopic": "openWB/set/lp/1/%Soc",
        "vin": "vin1"
    },
    {
        "chargeStateTopic": "openWB/lp/2/boolChargeStat",
        "chargingValue": "1",
        "socTopic": "openWB/set/lp/2/%Soc",
        "vin": "vin2"
    }
]
```

**Comment by nanomad** [comment]
I have a user in group chat with the same use case, I'll try to have him join this discussion and see what his thoughts are
