### ISSUE TITLE
Feature Request: dynamic polling during charging

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#52]
Given that now we can decode the estimated remaining charging time and SoC Target, I would suggest a new polling strategy:
- Get the current battery %
- Compute the number of polls needed for a specific resolution `polls = ceil(2 * (socTarget - current))`
- Compute the time between polls by looking at `remainingChargingTime`: `pollInterval = max(activeRefreshPeriod, ceil(remainingChargingTime/polls))`
- Re-evaluate this at every car charging status update

Overnight, for 20% of charge to recover in around 10h (1.8kW in AC), it would give a polling period of 
`pollInterval = 10*3600s/(2*20) = 900s`
with a resolution of 0.5%

Benefits are:
- Naturally throttling SAIC API requests, I've had the API get angry a lot of times if we keep polling it
- Avoid very frequent boot-ups of the TBOX, MCU and relative contactors, potentially wearing them down without a valid reason

**Comment by tosate** [comment]
We have learned that we run into trouble if we request the status too often. But the SoC doesn't even change so quickly.
If I get this right, then you want to calculate the number of polls to realize a resolution of 0.5%. This would probably save some requests in comparison to a static polling interval.

This sounds interesting to me. I am curious how the gateway would behave for me. I am mostly doing PV surplus charging. This means that the energy amount is not constant.

**Comment by tosate** [comment]
Using the battery management of the car to get the remaining charging time. Then calculating the progress and the number of polls based on this to avoid frequent boot-ups. This is genius! I like it a lot the longer I think about it.

**Comment by tosate** [comment]
Since I am currently charging, I am doing the math.

- SoC: 90.7%
- 20 polls until 100% for a resolution of 0.5%
- Remaining time 1:34:00

polling interval would then be every 282 seconds instead of 30 seconds.

**Comment by nanomad** [comment]
Exactly, the only question that remains is how to make it configurable via mqtt. Maybe by exposing the granularity %? (I.e. I'm fine with 2% as I don't really care about is t too much but some people may prefer 0.5 as the default)

**Comment by tosate** [comment]
Is the refresh/peroid/charging value exposed already to Home Assistant (auto-discovery)? It seems to work, but I can find it only on MQTT.

**Comment by nanomad** [comment]
Yep, it is exposed as a simple sensor
