### ISSUE TITLE
BMS, how can it be used?

### ISSUE THREAD

**Issue by DreamT80** [SAIC-iSmart-API/saic-python-mqtt-gateway#57]
This isn't an issue but rather a question.

I know that the Battery management system (BMS) can be used to calculate the SoH %. But how can the MQTT data be used to calculate this?

(A little bonus would of course be if the MQTT integration itself could calculate it and return as a parameter, but since it probably can be calculated on the "outside" maybe it's not a priority)

**Comment by nanomad** [comment]
Unfortunately I don't see a way of figuring that out. To get SoH% we need each cell reported voltage to compute the delta mV at 100% charge. 

One surrogate could be checking lastChargeEndingPower against the car raw battery  capacity (not exposed via the API) if the report SoC is 100% but I never checked if the value is correct or wrong

**Comment by DreamT80** [comment]
Ok, I see. It makes sense that this isn't exposed to the API, not that I think about it.
