### ISSUE TITLE
wrong totalBatteryCapacity for MG4 standard

### ISSUE THREAD

**Issue by manu78** [SAIC-iSmart-API/saic-python-mqtt-gateway#6]
Hi!

I'd say totalBatteryCapacity need some kind of parsing.
I found it is throwing me 72,5 kWh (as per 725/10) but I have a MG4 standard which only has 51,8 kWh. I was unable to find a conversion that makes any sense so I'll keep triying to find the factor or base transformation to reach the right figure.

Thank u for your amazing job! :muscle:

**Comment by Troon** [comment]
My 64kWh Trophy also shows that 72.5 figure, so it's not a question of conversion. I get these figures

```
saic/.../drivetrain/lastChargeEndingPower 65.4
saic/.../drivetrain/totalBatteryCapacity 72.5
```

which give the correct post-charge (but not live) % SoC as a ratio, but I don't see anything that looks like the actual kWh capacity.

Under the "511" JSON response, I see an `applicationData.basicVehicleStatus.extendedData1` value of 90 which matches my current % SoC but I don't know if that's a coincidence.

**Comment by manu78** [comment]
It seems not to be a coincidence, my figures also match. extendedData1 and actual soc, I mean. But not always. Sometimes I got 128. I'd say when car is not in active mode but I have to double check. I've put a filter in my nodered to avoid this 128 meanwhile

**Comment by tisoft** [comment]
extendedData1 is the SOC. Verified in the original ISMART app source code.

**Comment by hagene1505** [comment]
Hello, has this already been corrected? I use the Docker Image on my Synology NAS and unfortunately I get the wrong data displayed as the SOC.


extendedData1 is not sent to my broker. It would be great if that was adjusted.

Thanks for the great work and regards

**Comment by ChrisPiel70** [comment]
Hallo,

my Marvel-R schould have( in specification )  a  70 kWh HV Battery. I think it is a problem with SAIC.

![image](https://user-images.githubusercontent.com/68636799/235342730-53b7ee44-fb19-48bf-b6e0-b5f2feddef13.png)

Here are my values now.
 
![image](https://user-images.githubusercontent.com/68636799/235342482-1943d59c-82b1-4812-a449-9c4748e3f3a7.png)

Maybe i don't understand the API / DOCs but at the moment my SoC ist 77,9 ( % ), that is correct. Sometime i get a value of 102,3 ( % ).

When "totalbatteryCapacity" = 72,5 then soc_kwh cannot be 74,2, it should be 56,5 ( % )

Also ( i hope ) the values for "current", "voltage" and "power" are not real.

Keep up the great work. This is getting better with every new version.

**Comment by tisoft** [comment]
Total battery capacity is always 72.5. That is a wrong value coming from the SAIC API. I have not found a value in the API that corresponds to the real battery capacity.

`current = bmsPackCrnt * 0.05d - 1000.0d`
`voltage = bmsPackVol * 0.25`
`power = current * voltage / 1000d`

https://github.com/SAIC-iSmart-API/saic-java-client/blob/d02d83da71d41a51a0a52cd19ba132b47febe9c2/saic-java-mqtt-gateway/src/main/java/net/heberling/ismart/mqtt/VehicleState.java#L376-L394

**Comment by ChrisPiel70** [comment]
Hello,

that with Battery capacity is not really a problem.

Sorry, i was not questioning your calculations, but the values. When the cat is of, my normal values are  375V Voltage, 0,0A current  and 0,0 power. Why are the values for current and power so high? I don't think that 2300A really flowing in the car.
