### ISSUE TITLE
Q: ABRP - how to use 2 Smartphones with ABRP installed, with one car/VIN

### ISSUE THREAD

**Issue by cybersmart-eu** [SAIC-iSmart-API/saic-python-mqtt-gateway#68]
I don‘t know where to put this question. 
I have integrated ABRP with the gateway successfully and it works great for my car.

I wanted now to use it with ABRP on a second phone (linked to the same ABRP Premium account) but this fails.
 
The App on the second phone generates different user token and there is no way to add the same token as for the first App/Phone. Any ideas?

Did not try it, but what if in the environment variables I configure two different user tokens for the same VIN (two comma
separated entries LEJxxx=abcd-token, LEJxxx=xyz-toke), but  I guess it is intended the other way around for multiple VIN/cars. Maybe the dev of the ABRP connector knows this?

**Comment by nanomad** [comment]
Ah that's a damn good question. I don't think we ever tried. Iternio's Dev once told me that tokens are account wide and never revoked, so even if you use a new phone as long as the account is the same you should see the API connection go green.

**Comment by nanomad** [comment]
Yeah, let us know. Just make sure you drive the car around a bit so that it can send telemetry to ABRP

**Comment by Maart3nL** [comment]
I've set this up yesterday with ABRP running on my Mac logged in to my premium account, after adding the token en having it working on my Mac it was sync and worked without any extra steps on my iPhone logged in to the same account.

**Comment by cybersmart-eu** [comment]
ok, need to check. Maybe because both devices are registered with the same iCloud account … this is somehow synced. In my case the second device is registered with a different iCloud account but ABRP is registered with the same ABRP account.

Need to test while data is generated …

**Comment by cybersmart-eu** [comment]
can confirm - it works by just using the same ABRP account on the other smartphones
