### ISSUE TITLE
Trying to understand the docs

### ISSUE THREAD

**Issue by DreamT80** [SAIC-iSmart-API/saic-python-mqtt-gateway#7]
Hi,
I've successfullt installed the Python MQTT gateway, and can read values from the car.

However, I also want to run some commands. First of all, i'd like to run get the vehicle status, since I want to force a refresh of the  (the soc hasn't been updated in several hours, but it should since I'm charging). I understand how MQTT works, but I don't know which command to publish to achieve what I want. I've tried to read the documentation [here](https://github.com/SAIC-iSmart-API/documentation#vehicle-status) , but I don't understand it.
Can anybody get me on the right track, using Vehicle Status as an example?

**Comment by Tonno87** [comment]
To refresh your values simply publish a new message to the right  topic:

saic/xxxxx@gmail.com/vehicles/LSJExxxxxxxxx/refresh/mode/set

Message: force

After that the gateway will wake your car and refresh your values. There are many ways to do this, which system do you use?

**Comment by DreamT80** [comment]
Hi,
Thank you for your reply. I figured it out the day after i opened the issue, I should've told it here but I forgot.
I used saic-python-mqtt-gateway up until today, when I started to use saic-home-assistant-addon instead. Really neat to have it as an addon in HA, and it looks promising. Keep up the good work!

**Comment by Tonno87** [comment]
Working on it :)

**Comment by DreamT80** [comment]
Let me know if I can help testing! I don't have much time, but can help when there's time to spare.
