### ISSUE TITLE
range false reading 2046.0

### ISSUE THREAD

**Issue by mrniemand** [SAIC-iSmart-API/saic-python-mqtt-gateway#71]
a few times over a day i get an value of 2046.0 for the /drivetrain/range reading.
It happens in last and actual docker version.

**Comment by cybersmart-eu** [comment]
What car model do you have? I am since some days now collecting all date in influxDB and did not find any such peak for my MG5 SR Comfort 
![IMG_9692](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/77569473/7e35786f-cc90-4edf-868c-2586451a29ad)

**Comment by mrniemand** [comment]
i have an MG4 Luxury, in other countries is think it's the trophy version. I log with FHEM 
![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/964340/374020c3-ae60-48ab-ba17-23669b30e1cc)
.

**Comment by octvcdrc** [comment]
Same issue happening here
Exact same model : MG4 Luxury/Trophy
![firefox_jiaM1n34Ay](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/9086425/fd71c971-5010-44f3-aade-869b1061dc28)

**Comment by dudelburg** [comment]
![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/1192190/84c5ad9c-2969-47ed-8764-dea1436127ea)

I would like to add the filter for the interior temperature as well - it reports 87 °C some times. Car is MG4 Luxury MY2022.

**Comment by enrico1036** [comment]
I'm sure that the temperature problem is visible also on the MG iSmart app. Sometimes it goes exactly to 87°C. BTW would be great if there is a way to recognize those unreal values and discard them instead of showing.

**Comment by nanomad** [comment]
This is a known issue of the MG infotainment system. The same weird values are show in-car as well at times :(

**Comment by garthy** [comment]
So I also see this and it makes the graphs somewhat useless. 

Can we filter and just throw away these extreme values?

**Comment by nanomad** [comment]
Definitely, PR are more than welcome

**Comment by nanomad** [comment]
Fixed in 0.6.1 :)

**Comment by nanomad** [comment]
@layanto I could drop the  validation to 20460 if you prefer but we are fighiting against a "stupid" BMS producing weird data once in a while

**Comment by nanomad** [comment]
Testable in RC 0.7.0-rc8

**Comment by layanto** [comment]
@nanomad I think limiting to less than 2,046km will work for now. It will be a long while (if ever) before there is an MG with range more than 2,000km.
