### ISSUE TITLE
How to use the mobile phone as user name?

### ISSUE THREAD

**Issue by tefod-zz** [SAIC-iSmart-API/saic-python-mqtt-gateway#73]
When I first registered with the MG iSmart app, I stupidly used my mobile phone number. SMS arrived - everything worked back then including the "binding" with the car.
This app no longer sends authentication SMS's to Germany - so I cannot "unbind" the car via the app - so that I can create and bind the car to a user_name with an email address.

Question: can I use the phone number as the username and in what format?

**Comment by tisoft** [comment]
You can use the phone number in the following format:

`49-123456789`

Country Code dash phonenumber all without any leading zeros. 

https://github.com/evcc-io/evcc/discussions/5644#discussioncomment-6113113

**Comment by tosate** [comment]
I have also registered with my phone number. However, after specifying my email address in my profile, I could also use it as a username to login.

**Comment by tefod-zz** [comment]
@tisoft & @tosate - both hints worked flawlessfully. 
Thank you guys 🍻
