### ISSUE TITLE
Improvement : Condition to test if publisher to MQTT server is enable 

### ISSUE THREAD

**Issue by lbourdel** [SAIC-iSmart-API/saic-python-mqtt-gateway#74]
For my case, I don't need to send informations to MQTT server, I only need to send them to abrp live data.

Is it possible to disable MQTT publisher if mqtt_uri is not provided.

Thanks

**Comment by lbourdel** [comment]
I found a workaround to not run MQTT publisher:

in

class MqttGateway:
    def __init__(self, config: Configuration):
...
        # test to not publish to MQTT
        if self.configuration.mqtt_host != '0.0.0.0':
            self.publisher.connect()


Then give MQTT server's IP=0.0.0.0

In cmdline :
-mtcp://0.0.0.0:1883

**Comment by nanomad** [comment]
@lbourdel planned for 0.7.0, you'll just have to set MQTT_HOST to an empty string to disable MQTT publishing
