### ISSUE TITLE
Q: Range 

### ISSUE THREAD

**Issue by michpas** [SAIC-iSmart-API/saic-python-mqtt-gateway#78]
On my EU-luxury version:"

- with a SOC charged to 80%;
- The mqtt (drivetrain/range) reports 302. I assume this is expressed in miles. in KM would be 486 km.

The car has a WLTP range of 435 with SOC 100%.

Are there any solutions to get a more 'realistic' KM range number in Homeassistant (eg. apply a correction factor maybe?)

**Comment by nanomad** [comment]
Drivetrain/range should report the estimated range in the same unit reported by the car computer. Can you check what the official app currently says?

**Comment by michpas** [comment]
Thanks. Helpful. Its indeed reported in km.
