### ISSUE TITLE
Q: Data only fetched every 1-3 minutes not every 30 seconds

### ISSUE THREAD

**Issue by cybersmart-eu** [SAIC-iSmart-API/saic-python-mqtt-gateway#80]
Hi,

did somone else also experience that in practial use data is fetched in much lager intervals only than configured?

I understood the Interval default is 30 seconds when the car is running. Invervals are much longer.

**Comment by nanomad** [comment]
This is probably due to the slowness of the response from the API/Car. Nothing much that can be done.
The new scheduler I'm using locally ha stats about missed timers and such, and I've seen it complain about triggers being late

**Comment by cybersmart-eu** [comment]
I have not seen any replies so far faster than every 60-70 seconds. So maybe to reduce no of API calls against the server a 60s Interval as Default might make sense?

**Comment by aneantisor** [comment]
Hello, i expérience it too. But i disagree you the response time. Because i setup mqtt gateway 3 day ago and started with main version (0.3) witch made a call to api every 0.8secondes avergage. Even if the car was shutted down.

**Comment by cybersmart-eu** [comment]
Hmm, thats odd - every 0.8 seconds? Did you try to send another refresh interval via API? Default is 30s.
I now increased it to 60s via API. But your setup seems to have an issue then somehow

**Comment by aneantisor** [comment]
It was default setting. And i couldnt stop it by trying to set it differently. I figure it out with mqtt . It was spamming a lot.

**Comment by tosate** [comment]
To get usable data, you have to send multiple requests. We are querying the vehicle status and the charging status. Most of the time the first response does not contain any data and the request needs to be re-sent. Updating the data once means sending about 4 requests as you see in the log below.

```
saic-mqtt-gateway  | 2023-06-23 10:47:41,155 Starting new HTTPS connection (1): tap-au.soimt.com:443
saic-mqtt-gateway  | 2023-06-23 10:47:42,305 https://tap-au.soimt.com:443 "POST /TAP.Web/ota.mpv21 HTTP/1.1" 200 None
saic-mqtt-gateway  | 2023-06-23 10:47:42,310 API request returned no application data and no error message.
saic-mqtt-gateway  | 2023-06-23 10:47:57,323 Starting new HTTPS connection (1): tap-au.soimt.com:443
saic-mqtt-gateway  | 2023-06-23 10:47:57,436 https://tap-au.soimt.com:443 "POST /TAP.Web/ota.mpv21 HTTP/1.1" 200 None
saic-mqtt-gateway  | 2023-06-23 10:47:57,454 Starting new HTTPS connection (1): tap-au.soimt.com:443
saic-mqtt-gateway  | 2023-06-23 10:47:59,075 https://tap-au.soimt.com:443 "POST /TAP.Web/ota.mpv30 HTTP/1.1" 200 None
saic-mqtt-gateway  | 2023-06-23 10:47:59,081 API request returned no application data and no error message.
saic-mqtt-gateway  | 2023-06-23 10:48:14,091 Starting new HTTPS connection (1): tap-au.soimt.com:443
saic-mqtt-gateway  | 2023-06-23 10:48:14,189 https://tap-au.soimt.com:443 "POST /TAP.Web/ota.mpv30 HTTP/1.1" 200 None
saic-mqtt-gateway  | 2023-06-23 10:48:14,200 last activity: 2023-06-23 10:48:14
saic-mqtt-gateway  | 2023-06-23 10:48:14,206 Starting new HTTPS connection (1): tap-au.soimt.com:443
saic-mqtt-gateway  | 2023-06-23 10:48:14,323 https://tap-au.soimt.com:443 "POST /TAP.Web/ota.mp HTTP/1.1" 200 None
saic-mqtt-gateway  | 2023-06-23 10:48:14,327 0 messages received
saic-mqtt-gateway  | 2023-06-23 10:48:14,328 Waiting 60 seconds to check for new messages
```

In addition to querying the state, there is also the polling for notifications. If you are just looking at the frequency of requests, there might be more activity than expected. However, I agree with @cybersmart-eu that the vehicle data is effectively updated every 60-70 seconds.

Actually you don't want to query the API too often, because after a certain amount of requests you don't get any data. Version 0.4.0 will introduce a dynamic refresh period during charging that will prevent unnecessary status requests. The only use cases for frequent status updates are fast charging and driving.

**Comment by aneantisor** [comment]
I agree with @cybersmart-eu that the vehicle data is effectively updated every 60-70 seconds. 
I disagree, with the mg ismart official for Android. When i swipe down to refresh data while being on charging management page, i can clearly check that the power is changing at every refresh. Even if i refresh as fast as i can. 
I agree with the fact that there is maybe a limit to the number of call. Probably to limit the server's load.
Anyway, i tried a buggy version of java mqtt gateway. And Somewhere in the code, it was mentioned that "force" update could start looping and spamming mqtt.
That is not what i expérience today.
Yesterday while i was coming home, with the car. It did not update infos at 30s refresh rate. It was more 5mn.
