### ISSUE TITLE
Update to _internal/lwt causes Home Assistant to update the device_tracker entity state every second

### ISSUE THREAD

**Issue by dasadi** [SAIC-iSmart-API/saic-python-mqtt-gateway#82]
Every time the _internal/lwt topic receives an update  (online) due to the keepalive, the device_tracker entity updates the map location. This means, that homeassistant saves the location even if the car is not moving and redraws the map. Furthermore a lot of unnecessary history data is being saved, which in turn leads to poor performance when displaying the history using a map card.

https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/blob/a9fa48622a9bb4cf75ed1dd70d3e67039ede0f70/publisher.py#L88

Why is it necessary to  update the topic regularly? Shouldn't [will_set()](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/blob/a9fa48622a9bb4cf75ed1dd70d3e67039ede0f70/mqtt_publisher.py#L44C21-L44C29) take care of everything when the gateway is going offline?

**Comment by nanomad** [comment]
> Every time the _internal/lwt topic receives an update (online) due to the keepalive, the device_tracker entity updates the map location. This means, that homeassistant saves the location even if the car is not moving and redraws the map. Furthermore a lot of unnecessary history data is being saved, which in turn leads to poor performance when displaying the history using a map card.


This looks like a bug in HA, LWT is used as an availablity topic it is not used in the device tracker itself and it shouldn't cause an update of the device tracker state (which is linked to the GPS position)

> 
> https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/blob/a9fa48622a9bb4cf75ed1dd70d3e67039ede0f70/publisher.py#L88
> 
> Why is it necessary to update the topic regularly? Shouldn't [will_set()](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/blob/a9fa48622a9bb4cf75ed1dd70d3e67039ede0f70/mqtt_publisher.py#L44C21-L44C29) take care of everything when the gateway is going offline?

I found that when the broker is under heavy load it may disconnect temporarly from MQTT. This in turn will trigger a "False" to be published in the LWT topic. When the broker re-connects it doesn't publish a "True" again (despite being instructed to do so) and the car remains unavailable in HA

**Comment by nanomad** [comment]
@dasadi Please test ghcr.io/nanomad/saic-python-mqtt-gateway/saic-mqtt-gateway:0.4.0-rc5 and check that:
- It fixes the update rate of the device_tracker integration
- The broker stays available in HA for a long period of time (as long as it is running). Please also run it with MQTT_LOG_LEVEL set to debug

**Comment by dasadi** [comment]
Thank you! I have it running now, I'll send you the findings in a day or two.

**Comment by jmccrohan** [comment]
@dasadi Thanks for filing this. I was wondering why my map card was taking an age to load. I thought it was because of the 60 sec polling interval while driving. I didn't realise it was updating every second.

Can you post a link to the HA bug once you've filed it please?

**Comment by dasadi** [comment]
@nanomad During the 3 days of testing I have the following findings:

- RC5 fixes the update rate of the device_tracker
- The broker stayed online in HA throughout the 3 days of testing without a single entity showing offline at any point

**Comment by dasadi** [comment]
This is the issue regarding the bug with the mqtt device_tracker platform in HA:
https://github.com/home-assistant/core/issues/98833

**Comment by jmccrohan** [comment]
@nanomad @dasadi What are you doing with your bloated HA `states` table? Are you waiting for the states to be deleted via the retention period, or did you craft SQL to remove the superfluous values?

**Comment by nanomad** [comment]
I keep everything for the retention period (10d). Actually, I've a separated InfluxDB that keeps everything forever so it's not a concern of mine😁
