### ISSUE TITLE
is an consumption SinceLastCharge per 100km available?

### ISSUE THREAD

**Issue by mrniemand** [SAIC-iSmart-API/saic-python-mqtt-gateway#87]
the car itself shows an consumption in kwh/100km since last charching in the display. Is this in the api also available?

**Comment by nanomad** [comment]
Unfortunately consumption data of any kind is not exposed via SAIC API.

**Comment by mrniemand** [comment]
I tried to calculate it with mileageSinceLastCharge and applicationData_chargeStatus_powerUsageSinceLastCharge but the results are confusing.
applicationData_chargeStatus_powerUsageSinceLastCharge  sounds like consumption  since last charge

**Comment by nanomad** [comment]
@mrniemand there was an issue with the range values published that prevented us from computing consumption figures. 
0.6.x will fix that. I've also exposed the "consumption of the day" and "consumption since last charge" values so that you can easily compute the consumption data in Wh/km

**Comment by nanomad** [comment]
Data is available in 0.6.0-rc4

There's an open question about battery capacity. Looks like we will have to switch to the net battery capacity instead of the raw one in order to get accurate consumption measures.

I'll run some tests tomorrow
