### ISSUE TITLE
Enter data in the Compose file

### ISSUE THREAD

**Issue by SBFfan** [SAIC-iSmart-API/saic-python-mqtt-gateway#9]
Hello,

I am not familiar with the syntax of the environment variables and I have tried a lot of things. 
But I always get an error: "Invalid MQTT URI scheme: , use tcp or ws".

Can someone post me an example or tell me what I am doing wrong. Thanks a lot

 container_name: "saic-mqtt-gateway"
    environment:
      - MQTT_URI="tcp://192.168.2.151:1883"
      - MQTT_USER="admin"

**Comment by tosate** [comment]
You should not modify the docker-compose.yml file. Instead, you hide your secret information in the .env file. There is even a sample .env file in the repository.
