### ISSUE TITLE
Q: saic/_internal/lwt polling State every second

### ISSUE THREAD

**Issue by cybersmart-eu** [SAIC-iSmart-API/saic-python-mqtt-gateway#90]
Hi Devs,

I just found that my Message Counter goes up every second. Reason is polling saic/_internal/lwt  State (online/offline) every second. 
What exactly is queried here?
Does this mean API calls are generated every second?

**Comment by jmccrohan** [comment]
See #82.

**Comment by cybersmart-eu** [comment]
thx
