### ISSUE TITLE
Two way instruction not working

### ISSUE THREAD

**Issue by newbuilder22** [SAIC-iSmart-API/saic-python-mqtt-gateway#91]
Using python version. I have managed to see what the app is seeing but whilst the app allows changes to the vehicle- unlock doors etc, I cannot send this from home assistant. 
I am using mqqt mosquito broker and followed the instructions to auto discover. When I do select lock it quickly reverts back. 

Totally new to using mqqt on and add on so please be patient

**Comment by newbuilder22** [comment]
Can someone help?

**Comment by nanomad** [comment]
Does the door actually unlock? Or does the command fail completely? 

There's something called "optimistic" change in HA components that we could use for commands that we assume work but for which we don't get a feedback right after polling

**Comment by nanomad** [comment]
Fixed in 0.5.x, feel free to re-open if it still happens.
