### ISSUE TITLE
Control Current Ampere on charge

### ISSUE THREAD

**Issue by batmatjojojo** [SAIC-iSmart-API/saic-python-mqtt-gateway#92]
Hello, 

First of all, thank you for your developments. It's just impressive.

I'm looking for a feature that is load control with amperage limit 8A / 16A etc? 

Do you think it's possible to do this with the script at the moment? 

Thank you in advance for your help. 

Best regards

**Comment by nanomad** [comment]
Hi,

this has already been implemented in the development version.

**Comment by batmatjojojo** [comment]
Hello, 

That's great news, will it be included in the next realise in the "MAIN" version? 

Thanks again 

Best regards

**Comment by tosate** [comment]
Hi @nanomad, hi @batmatjojojo,

I am planning to publish version 0.4.0 soon. Unfortunately, I am currently very busy with other things.

**Comment by nanomad** [comment]
@batmatjojojo Fixed in 0.4.5, try it out
