### ISSUE TITLE
No connection anymore - even with App

### ISSUE THREAD

**Issue by cybersmart-eu** [SAIC-iSmart-API/saic-python-mqtt-gateway#95]
Hi, for 4 days now the api connect fails, also with the iSmart App. 
It seems to connect / login (no login failure) but vehicle scan not started. 
So it does not look like a gateway issue but maybe due to gateway usage something is blocked at SAIC?

Car: MG5
Gateway: 0.3.0

Was running smoothly so far. Container Logs don‘t provide much info:

`2023-10-02 10:07:41,040 handle_vehicle loop failed during SAIC API call,
Traceback (most recent call last):,
  File "/usr/src/app/./mqtt_gateway.py", line 97, in handle_vehicle,
    vehicle_status = self.update_vehicle_status(),
  File "/usr/src/app/./mqtt_gateway.py", line 117, in update_vehicle_status,
    vehicle_status_rsp_msg = self.saic_api.get_vehicle_status_with_retry(self.vin_info),
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 194, in get_vehicle_status_with_retry,
    return self.handle_retry(self.get_vehicle_status, vin_info),
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 458, in handle_retry,
    return self.__handle_retry_with_app_data(func, vin_info=vin_info, max_retries=max_retries),
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 500, in __handle_retry_with_app_data,
    raise SaicApiException(f'API request failed after {iteration} retries{additional_info}'),
saic_ismart_client.saic_api.SaicApiException: API request failed after 4 retries, error message: The remote control instruction failed, please try again later., `

Any ideas? Normally even if car would not be reachable the last Status update or other info should be available which is stored on SAIC servers.

BR
Uwe

**Comment by cybersmart-eu** [comment]
Update: Since noon today October 3rd it‘s working again. I disabled the Gateway container for more than 24h so maybe this helped solving it - I don‘t know. We will see. 
Maybe SAIC blocks an account or IP address, if too many requests are received within a given timeframe? Any ideas?

**Comment by tosate** [comment]
In fact, the API does not provide any data if a certain threshold has been exceeded. With the standard configuration you should not run into this. Did you modify the refresh periods?

**Comment by cybersmart-eu** [comment]
I did not reduced any value, I even incresed interval when running/charging from default 30s to 60s.
As it is working again now and no root cause in sight I will close the issue. Seems no others so far affected.
