### ISSUE TITLE
Issues with log in - password rejected

### ISSUE THREAD

**Issue by russellevans** [SAIC-iSmart-API/saic-python-mqtt-gateway#97]
Thanks for all the work but I wanted to share a problem I had.
(My fault for not reading the prompt in the app for numbers and letters in the app)

If you create your account with special char then in the home assistant SAIC MQTT Gateway (Python) it does not work.

The logs show a wrong password error even though it works to log in with the app.

Not sure if you wish to add this to the documentation......maybe I missed it

**Comment by tosate** [comment]
Do you have an ampersand in your password? This has been the issue in #97
[Have a look here.](https://stackoverflow.com/questions/41012216/why-cant-i-use-in-python-command-line)
