### ISSUE TITLE
Pull status after sending a command

### ISSUE THREAD

**Issue by kklem0** [SAIC-iSmart-API/saic-python-mqtt-gateway#98]
Is it possible to pull status everytime a command is sent?
Unlooking the door takes a long time to have the status updated.

**Comment by nanomad** [comment]
Right now we only poll once after sending a command.
We don't want to poll too often to avoid discharging the 12V battery if the command is sent but the car is unresponsive. 

We could implement something akin  to the "looking for charger" state where we poll every 120s up to 5 times I guess
@tosate , any ideas?

**Comment by nanomad** [comment]
@kklem0 Looks like it is fixed wih the latest 0.5.x gateway, feel free to re-open the issue if it still happens
